Repository aws/deep-learning-containers, pull requests merged in 2021-09, with the labels that each got.

#1297 [test] Add 'huggingface' pytest fixture
  huggingface/pytorch/buildspec.yml
  test/dlc_tests/conftest.py
  test/dlc_tests/release_candidate_integration/test_sm_profiler.py
Labels: huggingface

#1336 [doc] Update list of important packages on release notes
  release/dlc_release_information.py
  release/resources/important_dlc_packages.yml
Labels: documentation, improvement

#1278 [feature][tensorflow] Add support for DIY and SageMaker containers
  src/image.py
  src/image_builder.py
  src/utils.py
  tensorflow/buildspec-diy-sm-2-5.yml
  tensorflow/inference/docker/2.5/py3/.diy_sm_examples/Dockerfile.diy.cpu
  tensorflow/inference/docker/2.5/py3/.diy_sm_examples/Dockerfile.sagemaker.cpu
  tensorflow/inference/docker/2.5/py3/.diy_sm_examples/cu112/Dockerfile.diy.gpu
  tensorflow/inference/docker/2.5/py3/.diy_sm_examples/cu112/Dockerfile.sagemaker.gpu
  tensorflow/inference/docker/2.5/py3/cu112/Dockerfile.diy.gpu
  tensorflow/inference/docker/2.5/py3/cu112/Dockerfile.sagemaker.gpu
  tensorflow/training/docker/2.5/py3/.diy_sm_examples/Dockerfile.diy.cpu
  tensorflow/training/docker/2.5/py3/.diy_sm_examples/Dockerfile.sagemaker.cpu
  tensorflow/training/docker/2.5/py3/.diy_sm_examples/cu112/Dockerfile.diy.gpu
  tensorflow/training/docker/2.5/py3/.diy_sm_examples/cu112/Dockerfile.sagemaker.gpu
  tensorflow/training/docker/2.5/py3/cu112/Dockerfile.diy.gpu
  tensorflow/training/docker/2.5/py3/cu112/Dockerfile.sagemaker.gpu
  test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_performance_optimized_sm_training.py
  test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_performance_tensorflow_sm_training.py
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py
  test/dlc_tests/ec2/test_smclarify.py
  test/dlc_tests/ec2/test_smdebug.py
  test/dlc_tests/release_candidate_integration/test_sm_profiler.py
  test/dlc_tests/sanity/test_binary_visibility.py
  test/dlc_tests/sanity/test_canary_integration.py
  test/dlc_tests/sanity/test_dlc_labels.py
  test/dlc_tests/sanity/test_pre_release.py
  test/dlc_tests/sanity/test_pt_s3.py
  test/dlc_tests/sanity/test_safety_check.py
  test/dlc_tests/sanity/test_security_check.py
  test/dlc_tests/sanity/test_telemetry.py
  test/dlc_tests/sanity/test_torchvision.py
  test/dlc_tests/sanity/test_utility_installation.py
  test/test_utils/__init__.py
  test/testrunner.py
Labels: Size:XL, feature, diy_container, sagemaker_container

#1344 [build][pytorch][graviton]graviton pytorch image build
  pytorch/buildspec-graviton.yml
  pytorch/inference/docker/1.9/py3/Dockerfile.graviton
  src/start_testbuilds.py
Labels: build, pytorch, graviton

#1370 [bug] Fix bugs in dependency check test
  test/dlc_tests/sanity/test_pre_release.py
  test/test_utils/ec2.py
Labels: bug

#1364 [tensorflow][test]Added bokeh fix to TF2.5
  tensorflow/training/docker/2.5/py3/.diy_sm_examples/Dockerfile.diy.cpu
  tensorflow/training/docker/2.5/py3/.diy_sm_examples/cu112/Dockerfile.diy.gpu
  tensorflow/training/docker/2.5/py3/Dockerfile.cpu
  tensorflow/training/docker/2.5/py3/cu112/Dockerfile.diy.gpu
  tensorflow/training/docker/2.5/py3/cu112/Dockerfile.gpu
Labels: bug

#1377 [huggingface_tensorflow] Fix Tensorflow smd test
  test/sagemaker_tests/huggingface_tensorflow/training/integration/sagemaker/test_smdataparallel.py
Labels: bug

#788 [test][eks] EKS infrastructure
  eks_infrastructure/add_iam_identity.sh
  eks_infrastructure/build.sh
  eks_infrastructure/build_param.json
  eks_infrastructure/build_param.template
  eks_infrastructure/cluster-autoscalar-autodiscover.yaml
  eks_infrastructure/create_cluster.sh
  eks_infrastructure/delete_cluster.sh
  eks_infrastructure/eks_buildspec.yml
  eks_infrastructure/env_setup.sh
  eks_infrastructure/install_cluster_components.sh
  eks_infrastructure/namespace.yaml
  eks_infrastructure/rbac.yaml
  eks_infrastructure/upgrade_cluster.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow_custom_kfctl.sh
Labels: Size:XL

#1186 [build] Add safety report to docker image
  data/ignore_ids_safety_scan.json
  miscellaneous_dockerfiles/Dockerfile.common
  src/common_stage_image.py
  src/constants.py
  src/image.py
  src/image_builder.py
  src/metrics.py
  src/safety_report_generator.py
  src/utils.py
  test/dlc_tests/sanity/test_safety_report_file.py
Labels: Size:XL

#1383 [graviton][pytorch][test]Graviton pytorch add ec2 test
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
  test/test_utils/__init__.py
  test/test_utils/ec2.py
Labels: test, pytorch, ec2, graviton

#1385 [diy] Change DIY tag to ec2-ecs-eks
  tensorflow/buildspec-diy-sm-2-5.yml
  test/test_utils/__init__.py
Labels: diy_container
