Repository aws/deep-learning-containers, pull requests merged in 2021-08, with the labels that each got.

#1251 [pytorch][build] Added apt upgrades to Pt1.9-cpu,gpu,inf,train and updated Pillow to version 8.3.1
  pytorch/inference/docker/1.9/py3/Dockerfile.cpu
  pytorch/inference/docker/1.9/py3/cu111/Dockerfile.gpu
  pytorch/training/docker/1.9/py3/Dockerfile.cpu
  pytorch/training/docker/1.9/py3/cu111/Dockerfile.gpu
Labels: bug, dependencies

#1260 [release] Add PT 1.9 to release_images
  release_images.yml
Labels: documentation

#1263 [pytorch][test][sagemaker] Allow py38 option on PT SM tests
  test/sagemaker_tests/pytorch/inference/conftest.py
  test/sagemaker_tests/pytorch/training/conftest.py
Labels: improvement

#1262 [rc_integration] Remove dependency on SMProfiler repo buildspec
  test/dlc_tests/release_candidate_integration/test_sm_profiler.py
Labels: improvement

#1271 [gitops] Add code owners for new frameworks
  .github/CODEOWNERS
Labels: improvement

#1270 [pytorch][test][sagemaker] Fix PyTorch SM test retry logic
  test/sagemaker_tests/pytorch/__init__.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
Labels: bug, improvement

#1274 [gitops] Add updates to CODEOWNERS file
  .github/CODEOWNERS
Labels: improvement

#1269 [dev][test] Add a config option to run RC integration tests & SM local tests in PR
  dlc_developer_config.toml
  src/config.py
  src/start_testbuilds.py
  src/utils.py
  test/dlc_tests/release_candidate_integration/test_sm_profiler.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/test_utils/__init__.py
  test/testrunner.py
Labels: improvement

#1277 [pytorch][build][sagemaker] update SMDDP wheel for pt 1.9
  pytorch/training/docker/1.9/py3/cu111/Dockerfile.gpu
  test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
  test/sagemaker_tests/pytorch/training/resources/resnet18/main.py
Labels: bug, improvement, pytorch

#1279 [build][graviton] Add buildspec parsing for Graviton buildspecs and dockerfiles
  buildspec.yml
  dlc_developer_config.toml
  mxnet/buildspec-graviton.yml
  mxnet/inference/docker/1.8/py3/Dockerfile.graviton
  pytorch/buildspec-graviton.yml
  pytorch/inference/docker/1.9/py3/Dockerfile.graviton
  src/constants.py
  src/main.py
  tensorflow/buildspec-graviton.yml
  tensorflow/inference/docker/2.5/py3/Dockerfile.graviton
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/test_utils/__init__.py
Labels: build, mxnet, pytorch, tensorflow, graviton

#1287 [pytorch][build] install opencv using pip instead of conda
  pytorch/training/docker/1.9/py3/Dockerfile.cpu
  pytorch/training/docker/1.9/py3/cu111/Dockerfile.gpu
  test/sagemaker_tests/pytorch/inference/integration/local/test_serving.py
  test/sagemaker_tests/pytorch/training/integration/local/test_distributed_training.py
Labels: improvement

#1267 [MXNet][build] Relax pinned versions for requirements
  mxnet/training/docker/1.8/py3/Dockerfile.cpu
  mxnet/training/docker/1.8/py3/cu110/Dockerfile.gpu
Labels: improvement, mxnet

#1298 [release] Add huggingface_pytorch 1.8.1 inference containers
  release_images.yml
Labels: huggingface

#1299 [tensorflow][build] Add systemd upgrade to TF 2.4 inference gpu dockerfile
  tensorflow/inference/docker/2.4/py3/cu110/Dockerfile.gpu
Labels: improvement, tensorflow
