Repository aws/deep-learning-containers, pull requests merged in 2022-12, with the labels that each got.

#2372 [tensorflow][build][test] Tensorflow serving 2.11 release changes
  data/ignore_ids_safety_scan.json
  tensorflow/buildspec.yml
  tensorflow/inference/docker/2.11/py3/Dockerfile.cpu
  tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu
Labels: build, test, tensorflow, sanity, Size:S

#2421 [pytorch] [trcomp] Add support for PT 1.12 SM Training Compiler
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.trcomp.gpu
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ec2/test_smdebug.py
  test/dlc_tests/sanity/test_pre_release.py
  test/dlc_tests/sanity/test_telemetry.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
  test/test_utils/__init__.py
  test/testrunner.py
Labels: build, test, pytorch, ec2, sanity, Size:S, sagemaker_tests

#2472 TF2.11 EC2 Release for Training + Inference, SM Release for Inference
  release_images.yml
Labels: Size:S

#2475 [TensorFlow] Fix for TF2.11 Release
  release_images.yml
Labels: Size:XS

#2466 doc: remove eia images
  available_images.md
Labels: Size:XS, Size:S

#2473 [tensorflow][test][sagemaker] Fix regex in test to match output of training script.
  tensorflow/training/docker/2.10/py3/Dockerfile.cpu
  tensorflow/training/docker/2.10/py3/cu112/Dockerfile.gpu
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py
Labels: build, test, tensorflow, Size:XS, Size:S, sagemaker_tests

#2478 [pytorch] [trcomp] Updated binaries with CVE fix for PT.12 SM Training Compiler
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.sagemaker.trcomp.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.trcomp.gpu
  test/dlc_tests/sanity/test_pre_release.py
  test/test_utils/__init__.py
Labels: build, test, pytorch, ec2, sanity, Size:XS, Size:S, sagemaker_tests

#2479 [test] Fix dpkg lock-frontend error when installing python
  test/test_utils/ec2.py
  test/test_utils/sagemaker.py
Labels: Size:S

#2464 Remove python kernel installed by sparkmagic
  tensorflow/buildspec-2-10.yml
  tensorflow/training/buildspec-2-10.yml
  tensorflow/training/docker/2.10/py3/Dockerfile.cpu
  tensorflow/training/docker/2.10/py3/cu112/Dockerfile.gpu
Labels: build, tensorflow, Size:XS, Size:S

#2480 [TensorFlow] Available Images Update for TF2.11 Release
  .release_images_template.yml
  available_images.md
  release_images.yml
Labels: Size:S

#2482 sm local support for pt trcomp
  test/test_utils/sagemaker.py
  test/testrunner.py
Labels: Size:XS

#2484 [release][TF][PT] release TF2.10.1 training and PT 1.12 trcomp images
  release_images.yml
Labels: Size:S

#2487 doc: PT-1.13 python version
  available_images.md
Labels: Size:XS

#2430 tensorflow 2.10 inference image build
  tensorflow/buildspec-2-10.yml
Labels: build, test, tensorflow, sanity, Size:S

#2488 [PT][trcomp] update available_images.md with PT1.12 trcomp DLC
  available_images.md
Labels: Size:XS

#2462 [re-release][sagemaker][PT-1.12.1] patch code injection CVE
  pytorch/buildspec-1-12.yml
  pytorch/training/docker/1.12/py3/Dockerfile.cpu
  pytorch/training/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.gpu
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, test, pytorch, tensorflow, sanity, Size:S, sagemaker_tests

#2496 Remove regular frameworks from codeowners file
  .github/CODEOWNERS
Labels: Size:XS

#2470 [pytorch][sagemaker] Prep for PT 1.13 SM release
  pytorch/buildspec.yml
  pytorch/inference/docker/1.13/py3/Dockerfile.cpu
  pytorch/inference/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
Labels: build, test, pytorch, ec2, Size:S

#2494 Tf2 9 inference images dec2022
  tensorflow/buildspec-2-9.yml
Labels: build, tensorflow, Size:S

#2471 [test] Add p4de instance test on SM
  dlc_developer_config.toml
  pytorch/buildspec-1-12.yml
  src/config.py
  src/start_testbuilds.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/sagemaker_tests/__init__.py
  test/sagemaker_tests/pytorch/training/__init__.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
  test/test_utils/__init__.py
  test/test_utils/sagemaker.py
Labels: src, build, test, pytorch, sanity, Size:S, sagemaker_tests

#2500 Bug fix to cleanup dev config toml file
  dlc_developer_config.toml
Labels: Size:XS

#2499 pinning packaging to 21.3 for sm tests
  test/sagemaker_tests/tensorflow/inference/requirements.txt
Labels: test, Size:XS, sagemaker_tests

#2505 Delisting TF 2.6 Trcomp image
  available_images.md
Labels: Size:XS

#2501 [release][TF] release TF 2.9.2 Inference images
  release_images.yml
Labels: Size:S

#2508 [release][pytorch] PT 1.13.0 patch release and PT 1.13.0 SM "cpu" release
  release_images.yml
Labels: Size:XS

#2489 [pytorch][ec2][sagemaker][build][test] patched binaries and new armcl install
  pytorch/inference/docker/1.12/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/Dockerfile.graviton.cpu
  pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json
  test/sagemaker_tests/pytorch/inference/conftest.py
  test/sagemaker_tests/pytorch/inference/requirements.txt
  test/test_utils/__init__.py
  test/test_utils/ec2.py
Labels: build, test, pytorch, benchmark, Size:S, sagemaker_tests

#2456 [mxnet] [build] Mxnet 1 9 mkl blas
  mxnet/buildspec.yml
  mxnet/inference/docker/1.9/py3/Dockerfile.cpu
  mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu
  test/dlc_tests/sanity/test_mxnet_blas_mkl.py
Labels: build, test, mxnet, tensorflow, sanity, Size:XS, Size:S

#2507 Patching PyTorch 1.12 for EC2 and SM for image release
  pytorch/buildspec-1-12.yml
  pytorch/inference/docker/1.12/py3/Dockerfile.cpu
  pytorch/inference/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.gpu
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.gpu
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, pytorch, Size:S

#2511 [release][graviton] PT and TF graviton re-release for patches
  release_images.yml
Labels: Size:S

#2461 [NEURON][MXNET][BUILD] - Neuron sdk 2.5.0 release
  data/ignore_ids_safety_scan.json
  mxnet/buildspec-neuron.yml
  mxnet/inference/docker/1.8/py3/sdk2.5.0/Dockerfile.neuron
  mxnet/inference/docker/1.8/py3/sdk2.5.0/Dockerfile.neuron.os_scan_allowlist.json
  test/dlc_tests/sanity/test_dlc_labels.py
  test/dlc_tests/sanity/test_safety_check.py
  test/test_utils/__init__.py
Labels: build, test, mxnet, sanity, Size:S

#2512 [Sagemaker][Test] Rectify packaging version for MxNet 1.9 SM tests
  test/sagemaker_tests/mxnet/inference/requirements.txt
Labels: test, Size:XS, sagemaker_tests

#2502 update PT1.13 EC2 training binaries
  pytorch/buildspec.yml
  pytorch/training/docker/1.13/py3/Dockerfile.cpu
  pytorch/training/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/training/docker/1.13/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
Labels: build, test, pytorch, ec2, Size:S

#2503 [TF][2.10.1] Release TF 2.10.1 inference DLCs
  tensorflow/buildspec-2-10.yml
  tensorflow/inference/docker/2.10/py3/Dockerfile.cpu
  tensorflow/inference/docker/2.10/py3/cu112/Dockerfile.gpu
Labels: build, tensorflow, Size:XS

#2514 Added configurations to release PyTorch Inference 1.12
  release_images.yml
Labels: Size:S

#2515 [Release] MxNet 1.9 image release_images.yml changes
  release_images.yml
Labels: Size:S

#2516 release PT1.13 EC2 Training DLC
  release_images.yml
Labels: Size:S

#2518 [release] Add PT 1.12.1 training DLCs to release
  release_images.yml
Labels: Size:S

#2513 Release DJL 0.20.0 containers
  release_images.yml
Labels: Size:XS, Size:S

#2520 tf 2.10.1 release images
  release_images.yml
Labels: Size:S

#2517 [NEURON][BUILD][TF] - Add the new high sev CVE to allow list.
  tensorflow/inference/docker/1.15/py3/sdk2.5.0/Dockerfile.neuron.os_scan_allowlist.json
  test/dlc_tests/sanity/test_ecr_scan.py
Labels: build, test, tensorflow, sanity, Size:S

#2519 Patching Tensorflow 2.8
  tensorflow/buildspec-2-8.yml
  tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
  tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
  test/dlc_tests/sanity/test_pre_release.py
Labels: build, test, tensorflow, sanity, Size:S

#2521 adding tf 2.10.1 inference images
  available_images.md
Labels: Size:XS, Size:S

#2526 Add release info for DJL; Fix AG buildspec
  autogluon/buildspec.yml
  available_images.md
  release_images.yml
Labels: build, Size:S, autogluon

#2525 Updating release YAML to release AG 0.6.1
  release_images.yml
Labels: Size:XS

#2527 Release mx1.8,tf1.15.5,tf2.8.0 for sdk2.5.0
  release_images.yml
Labels: Size:S

#2522 [NEURON][BUILD][PT] - Add the new cves to allowlist
  pytorch/inference/docker/1.12/py3/sdk2.5.0/Dockerfile.neuron.os_scan_allowlist.json
Labels: build, pytorch, Size:S

#2532 AG 0.6.1 Training Security Fixes
  autogluon/training/docker/0.6/py3/Dockerfile.cpu
  autogluon/training/docker/0.6/py3/Dockerfile.cpu.os_scan_allowlist.json
  autogluon/training/docker/0.6/py3/cu113/Dockerfile.gpu
  autogluon/training/docker/0.6/py3/cu113/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, Size:S, autogluon

#2533 Releasing Training AG 0.6.1
  release_images.yml
Labels: Size:S

#2529 [NEURON][PT][BUILD] - Add cve to allowlist
  pytorch/inference/docker/1.12/py3/sdk2.5.0/Dockerfile.neuron.os_scan_allowlist.json
Labels: build, pytorch, Size:S

#2530 [NEURON][RELEASE] - Update the available images for sdk2.5.0
  available_images.md
Labels: Size:XS

#2534 [NEURON][PT] - Update the release images.
  release_images.yml
Labels: Size:XS

#2535 Remove PT 1.12 non-neuron images
  release_images.yml
Labels: Size:S

#2528 [TensorFlow] TF 2.8.4
  tensorflow/buildspec-2-8.yml
  tensorflow/training/buildspec-2-8.yml
  tensorflow/training/docker/2.8/py3/Dockerfile.cpu
  tensorflow/training/docker/2.8/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.8/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.8/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu
  tensorflow/training/docker/2.8/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, tensorflow, Size:S

#2538 Patching package certifi in Tensforflow 2.8 GPU and CPU images
  tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
  tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
Labels: build, tensorflow, Size:XS, Size:S

#2541 [autogluon][doc] AutoGluon 0.6.1 available images update
  available_images.md
Labels: Size:XS, Size:S

#2544 Modifying buildspec to build RCs
  tensorflow/buildspec-2-8.yml
Labels: build, tensorflow, Size:S

#2469 [pytorch][build] PT 1.11 patching
  data/ignore_ids_safety_scan.json
  pytorch/buildspec-1-11-cu115.yml
  pytorch/buildspec-1-11.yml
  pytorch/inference/docker/1.11/py3/Dockerfile.cpu
  pytorch/inference/docker/1.11/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.11/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.11/py3/cu113/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.11/py3/cu113/Dockerfile.gpu
  pytorch/inference/docker/1.11/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.11/py3/cu115/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.11/py3/cu115/Dockerfile.gpu
  pytorch/inference/docker/1.11/py3/cu115/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  src/pin_git_modules.py
Labels: src, build, pytorch, Size:XS, Size:S

#2537 Add Neuron SDK 2.5.0 PT1.12 to available images
  available_images.md
Labels: Size:XS

#2545 Add schema to release tensorflow 2.8.4 images
  release_images.yml
Labels: Size:S

#2540 Re-release of PT 1.13.1
  data/ignore_ids_safety_scan.json
  pytorch/buildspec.yml
  pytorch/inference/docker/1.13/py3/Dockerfile.cpu
  pytorch/inference/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, pytorch, Size:XS, Size:S

#2549 Update config to release PyTorch 1.13.1
  release_images.yml
Labels: Size:XS

#2542 [PT-1.12.1][SM] re-release with the deprecated smdebug hooks removed from binary, fix PT-1.13.1 CVE checks
  pytorch/buildspec-1-12.yml
  pytorch/training/docker/1.12/py3/Dockerfile.cpu
  pytorch/training/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.gpu
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/training/docker/1.13/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  test/dlc_tests/container_tests/bin/pytorch_tests/setupPyTorchBackendTest
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchMpi
Labels: build, test, pytorch, sanity, Size:XS, Size:S

#2548 [Release][PT-1.13.1][EC2]
  pytorch/buildspec.yml
  pytorch/training/docker/1.13/py3/Dockerfile.cpu
  pytorch/training/docker/1.13/py3/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
Labels: build, test, pytorch, sanity, Size:S

#2551 refactor: update the release specs
  release_images.yml
Labels: Size:XS, Size:S

#2553 refactor: unpin sagemaker in test requirement
  test/sagemaker_tests/pytorch/training/requirements.txt
Labels: test, Size:XS, sagemaker_tests
