Repository aws/deep-learning-containers, pull requests merged in 2022-07, with the labels that each got.

#2047 [release][pytorch] PT1.12 release_image.yml change
  .release_images_template.yml
  release_images.yml
Labels: Size:S

#2048 [Doc][Pytorch] PT112 E3 available_images update
  available_images.md
Labels: Size:S

#2066 Update opencv to 4.6.0 for PT 1.10 graviton
  pytorch/inference/docker/1.10/py3/Dockerfile.graviton.e3.cpu
  test/dlc_tests/benchmark/ec2/mxnet/test_performance_mxnet_inference.py
  test/dlc_tests/benchmark/ec2/pytorch/inference/test_performance_pytorch_inference.py
  test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
  test/dlc_tests/sanity/test_telemetry.py
  test/test_utils/__init__.py
Labels: src, build, test, pytorch, ec2, benchmark, sanity, Size:XS, Size:S

#2084 Add test to block specific releases
  test/dlc_tests/sanity/test_pre_release.py
Labels: test, sanity, Size:XS

#2082 [build][huggingface_tensorflow] HF TF 2.6 cve fix
  data/ignore_ids_safety_scan.json
Labels: build, huggingface, Size:XS

#2028 [tensorflow] [trcomp] [huggingface] add trcomp 2.6 dockerfile with latest CVE fixes
  data/ignore_ids_safety_scan.json
  huggingface/tensorflow/training/docker/2.6/py3/cu112/Dockerfile.trcomp.gpu
  test/dlc_tests/sanity/test_pre_release.py
Labels: build, test, huggingface, sanity, Size:XS, Size:S

#2081 add triton 22.05 container to docs
  available_images.md
Labels: Size:XS

#2078 Security patch for Autogluon 0.3.2 and bug fix for test cuda path failures
  autogluon/inference/docker/0.3.2/py3/Dockerfile.cpu
  autogluon/training/docker/0.3.2/py3/Dockerfile.cpu
  autogluon/training/docker/0.3.2/py3/cu112/Dockerfile.gpu
  data/ignore_ids_safety_scan.json
  test/dlc_tests/sanity/test_pre_release.py
  test/test_utils/__init__.py
Labels: build, test, sanity, Size:XS, Size:S, autogluon

#2101 release trcomp TF2.6
  release_images.yml
Labels: Size:XS

#2041 Re-release of PT1.11 for Sagemaker model parallel v1.10.0
  pytorch/training/docker/1.11/py3/cu113/Dockerfile.gpu
  pytorch/training/docker/1.11/py3/cu115/Dockerfile.gpu
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/memory_tracker.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/train_gpt_simple.py
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#2099 Add HC support to SageMaker DLC
  pytorch/buildspec-1-11-0.yml
  pytorch/training/docker/1.10/py3/Dockerfile.sagemaker.cpu
  pytorch/training/docker/1.10/py3/cu113/Dockerfile.sagemaker.gpu
  tensorflow/buildspec-2-6.yml
  tensorflow/buildspec-2-7.yml
  tensorflow/buildspec-2-8.yml
  tensorflow/buildspec.yml
  tensorflow/training/docker/2.6/py3/Dockerfile.cpu
  tensorflow/training/docker/2.6/py3/cu112/Dockerfile.gpu
  tensorflow/training/docker/2.7/py3/Dockerfile.sagemaker.cpu
  tensorflow/training/docker/2.7/py3/cu112/Dockerfile.sagemaker.gpu
  test/dlc_tests/sanity/test_pre_release.py
  test/sagemaker_tests/pytorch/training/integration/local/test_single_machine_training.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pt_s3_plugin.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_training_smdebug.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_horovod.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smdataparallel.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/resources/smmodelparallel/smmodelparallel_hvd2_conv.py
  test/test_utils/sagemaker.py
Labels: build, test, pytorch, tensorflow, sanity, Size:S, sagemaker_tests

#2102 [pytorch][build] Rename PT 1.11 buildspec
  pytorch/buildspec-1-11.yml
Labels: build, pytorch, Size:XS

#2098 Huggingface sagemaker test fix
  test/sagemaker_tests/huggingface_tensorflow/training/integration/local/test_placeholder.py
  test/testrunner.py
Labels: test, Size:XS, Size:S, sagemaker_tests

#2104 Re-release HF TF 2.6
  release_images.yml
Labels: Size:XS

#2097 Security Patch for Autogluon 0.3.2 - install OSS compliance package
  autogluon/inference/docker/0.3.2/py3/Dockerfile.cpu
Labels: build, test, sanity, Size:XS, Size:S, autogluon

#2108 Modified release images file for Autogluon 0.3.2 release
  release_images.yml
Labels: Size:S

#2107 [pytorch][build] fix dgl test
  test/dlc_tests/container_tests/bin/dgl_tests/parse_dgl_results.py
  test/dlc_tests/container_tests/bin/dgl_tests/testDGLHelper
  test/dlc_tests/container_tests/bin/dgl_tests/testMXNetDGL
  test/dlc_tests/container_tests/bin/dgl_tests/testPyTorchDGL
Labels: Size:S

#2111 Bukeao habana DLC 1.5.0 release 2 CVE patch
  test/dlc_tests/sanity/test_pre_release.py
Labels: test, sanity, Size:XS

#2112 [pytorch][test] update 0.9.x GCN SM test
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_dgl.py
  test/sagemaker_tests/pytorch/training/resources/dgl-gcn/train.py
  test/sagemaker_tests/pytorch/training/resources/dgl-gcn/train_dgl_lt_09x.py
Labels: test, Size:S, sagemaker_tests

#2114 Re-release PT1.11 and PT1.10 training images with latest sagemaker-pytorch-training toolkit
  pytorch/buildspec-1-10.yml
  pytorch/buildspec-1-11.yml
  pytorch/training/docker/1.10/py3/Dockerfile.sagemaker.cpu
  pytorch/training/docker/1.10/py3/cu113/Dockerfile.sagemaker.gpu
  pytorch/training/docker/1.11/py3/Dockerfile.cpu
  pytorch/training/docker/1.11/py3/cu113/Dockerfile.gpu
Labels: build, pytorch, Size:S

#2113 Release Habana Synai1.5.0 images
  release_images.yml
Labels: Size:XS

#2092 Update HF TrComp PT 1.10 build to prepare for anaconda removal
  huggingface/pytorch/training/docker/1.10/py3/cu113/Dockerfile.trcomp.gpu
  test/dlc_tests/sanity/test_binary_visibility.py
  test/test_utils/__init__.py
Labels: build, test, huggingface, sanity, Size:XS, Size:S

#2115 [pytorch] [test] update testTorchdata bash script
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
Labels: Size:XS

#2116 Remove Pt1.11 CPU GPU from release_images.yml
  release_images.yml
Labels: Size:S

#2093 Security Patch of opencv-python for PyTorch 1.10
  pytorch/buildspec-1-10.yml
  pytorch/training/docker/1.10/py3/Dockerfile.e3.cpu
  pytorch/training/docker/1.10/py3/cu113/Dockerfile.e3.gpu
  pytorch/training/docker/1.10/py3/cu113/Dockerfile.sagemaker.gpu
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/train_gpt_simple.py
  test/test_utils/sagemaker.py
Labels: build, test, pytorch, Size:S, sagemaker_tests

#2119 Added release image template for PT 1.10
  release_images.yml
Labels: Size:S

#2103 [Pytorch][release] PT1.12 SM release_image.yml change
  release_images.yml
Labels: Size:S

#2118 Add Habana SynAI1.5 images to available_images.yml
  available_images.md
Labels: Size:XS

#2123 Modifying PT 1.10 buildspec to generate inference image RCs
  pytorch/buildspec-1-10.yml
Labels: build, pytorch, Size:S

#2049 [Doc][Pytorch][SM] PT112 SM available_image update
  available_images.md
Labels: Size:XS

#2126 Release PT 1.11 sagemaker training images
  release_images.yml
Labels: Size:S

#2128 Releasing PyTorch 1.10 inference images
  release_images.yml
Labels: Size:S

#2125 Huggingface Pytorch 1.10 cve fix
  data/ignore_ids_safety_scan.json
Labels: build, huggingface, Size:XS

#2127 Add CGK region to the available_images.md file
  available_images.md
Labels: Size:XS

#2132 Release HF PT 1.10.2 inference and training
  release_images.yml
Labels: Size:S

#2129 Remove out of support images from available_images.md
  available_images.md
Labels: Size:S

#2137 Update available images file with anaconda license
  available_images.md
Labels: Size:XS

#2138 Update release images for Tr Comp
  release_images.yml
Labels: Size:XS
