Repository aws/deep-learning-containers, pull requests merged in 2023-12, with the labels that each got.

#3546 profiler for pt2.1
  pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu
  test/sagemaker_tests/pytorch/training/integration/local/test_smppy_local.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smppy.py
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#3547 empty release configuration
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3550 chore: Temporarily ignoring HIGH to release CRITICAL fixes
  huggingface/tensorflow/inference/docker/2.11/py3/Dockerfile.cpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3523 HuggingFace PT Inference/training CVE fix
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu.os_scan_allowlist.json
  huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
  huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:XS, Size:S

#3556 [djl-serving] Patch 0.25.0-0.23.0 LMI DLC images
  release_images_inference.yml
Labels: Size:S

#3559 [djl-serving] clear out djl images release_images_inference.yml
  release_images_inference.yml
Labels: Size:S

#3529 [Build][Test] Tensorflow inference 2.12
  src/autopr_caller.py
  src/patch_helper.py
  src/start_testbuilds.py
  src/utils.py
  test/dlc_tests/sanity/test_ecr_scan.py
  test/dlc_tests/sanity/test_pre_release.py
  test/dlc_tests/sanity/test_telemetry.py
Labels: src, test, sanity, Size:XS, Size:S

#3554 TGI Available Images Update
  available_images.md
Labels: Size:XS

#3560 [djl-serving] Patch 0.25.0-0.23.0 LMI DLC images
  release_images_inference.yml
Labels: Size:S

#3555 [TF2.12][TF2.13] Re-Release TF2.12+TF2.13 SM GPU and CPU
  tensorflow/training/buildspec-2-12.yml
  tensorflow/training/docker/2.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.12/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.12/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.12/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  tensorflow/training/docker/2.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.13/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.13/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  test/dlc_tests/sanity/test_telemetry.py
Labels: build, test, tensorflow, sanity, Size:XS, Size:S

#3561 chore: Fixing HF TF release file
  release_images_inference.yml
Labels: Size:XS

#3562 Add release config for Triton v23.10
  .github/CODEOWNERS
  release_images_inference.yml
Labels: Size:XS, Size:S

#3564 [djl-serving] patch djl 0.23, 0.24, and 0.25 TNX containers
  release_images_inference.yml
Labels: Size:S

#3565 [djl-serving] patch djl 0.24 FasterTransformer containers
  release_images_inference.yml
Labels: Size:S

#3568 [djl-serving] patch djl 0.24 TNX containers
  release_images_inference.yml
Labels: Size:XS

#3567 Re-Release TF2.12 & TF2.13 Sagemaker Images
  release_images_training.yml
Labels: Size:S

#3571 Updates from re:Invent 2023
  pytorch/inference/buildspec-1-13-ec2.yml
  pytorch/inference/buildspec-1-13-sm.yml
  pytorch/training/docker/2.0/py3/Dockerfile.cpu
  pytorch/training/docker/2.0/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  release/resources/important_dlc_packages.yml
  tensorflow/inference/buildspec-ec2.yml
  tensorflow/inference/buildspec-sm.yml
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.gpu
  test/dlc_tests/conftest.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/__init__.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smart_sifting.py
  test/sagemaker_tests/pytorch/training/resources/smart_sifting/__init__.py
  test/sagemaker_tests/pytorch/training/resources/smart_sifting/requirements.txt
  test/sagemaker_tests/pytorch/training/resources/smart_sifting/train_plt_smart_sifting.py
  test/sagemaker_tests/pytorch/training/utils/__init__.py
Labels: src, build, test, pytorch, tensorflow, Size:S, sagemaker_tests

#3576 [TensorFlow][SM Tests] Update NO_P3_REGIONS for SM Tests
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py
Labels: test, Size:XS, sagemaker_tests

#3587 1P Code Owner Change
  .github/CODEOWNERS
Labels: Size:XS

#3572 chore: patch vulnerabilities
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu.os_scan_allowlist.json
  huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
  huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, huggingface, Size:XS, Size:S

#3585 Release PT HF 2.0.0 and 1.13.1 images
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu.os_scan_allowlist.json
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
Labels: src, build, test, huggingface, sanity, Size:S

#3590 Patch sagemaker-pytorch-2.1 inference cpu and gpu DLC
  data/ignore_ids_safety_scan.json
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/2.1/py3/Dockerfile.cpu
  pytorch/inference/docker/2.1/py3/cu118/Dockerfile.gpu
  test/dlc_tests/sanity/test_safety_check.py
Labels: build, test, pytorch, sanity, Size:S, sagemaker_tests
