Repository aws/deep-learning-containers, pull requests merged in 2023-07, with the labels that each got.

#3141 [HuggingFace] Release HF PT1.13
  release_images_inference.yml
Labels: Size:S

#3112 [test][ec2] Fix EFA test instance creation logic to prevent unnecessary test executions
  dlc_developer_config.toml
  test/test_utils/ec2.py
Labels: Size:S

#3102 [test][sagemaker] Parallelize all SageMaker Integration remote tests
  test/sagemaker_tests/__init__.py
  test/sagemaker_tests/autogluon/inference/integration/sagemaker/test_serving.py
  test/sagemaker_tests/autogluon/inference/requirements.txt
  test/sagemaker_tests/autogluon/training/requirements.txt
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_diffusers_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_hub_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_ipex_inference.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_neuron_hosting.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_neuronx_hosting.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_sm_trained_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_speech_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_torch_compile.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_vision_model.py
  test/sagemaker_tests/huggingface/inference/requirements.txt
  test/sagemaker_tests/huggingface_pytorch/training/conftest.py
  test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
  test/sagemaker_tests/huggingface_tensorflow/training/requirements.txt
  test/sagemaker_tests/pytorch/__init__.py
  test/sagemaker_tests/pytorch/inference/requirements.txt
  test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_mnist_inductor.py
  test/sagemaker_tests/pytorch/training/requirements.txt
  test/sagemaker_tests/tensorflow/inference/requirements.txt
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/test_tfs.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/util.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt
  test/test_utils/sagemaker.py
Labels: build, test, huggingface, pytorch, tensorflow, Size:S, sagemaker_tests

#3142 [HuggingFace] Release HF pt1.13 CPU
  release_images_inference.yml
Labels: Size:XS, Size:S

#3137 deleting outdated docker files for pytorch-eia-1.3.1
  pytorch/inference/docker/1.3.1/py3/Dockerfile.eia
Labels: build, pytorch, Size:S

#3144 [Huggingface][Release] Update Sagemaker Version for HF Release
  test/sagemaker_tests/huggingface/inference/requirements.txt
Labels: test, Size:XS, sagemaker_tests

#3145 Update sagemaker version for HF Release
  test/sagemaker_tests/huggingface/inference/requirements.txt
Labels: test, Size:XS, sagemaker_tests

#3146 [HuggingFace] Revert updates to requirements file for hf
  test/sagemaker_tests/huggingface/inference/requirements.txt
Labels: test, Size:S, sagemaker_tests

#3151 [test][sagemaker] Unpin requirements on SM tests for HF PyTorch DLCs
  test/sagemaker_tests/huggingface/inference/requirements.txt
  test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
  test/sagemaker_tests/pytorch/inference/requirements.txt
  test/sagemaker_tests/pytorch/training/requirements.txt
Labels: test, Size:S, sagemaker_tests

#3119 update SM toolkit for HF PyTorch inference v2.0
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: src, build, huggingface, Size:XS, Size:S

#3155 Add label to ts image
  pytorch/inference/buildspec-1-13-neuron.yml
  pytorch/inference/buildspec-1-13-neuronx.yml
  pytorch/inference/buildspec-1-13.yml
  pytorch/inference/buildspec-eia.yml
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/buildspec-neuron.yml
  pytorch/inference/buildspec-neuronx.yml
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/1.13/py3/Dockerfile.cpu
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/inference/docker/1.13/py3/sdk2.10.0/Dockerfile.neuron
  pytorch/inference/docker/1.13/py3/sdk2.10.0/Dockerfile.neuronx
  pytorch/inference/docker/1.13/py3/sdk2.9.0/Dockerfile.neuronx
  pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  pytorch/inference/docker/2.0/py3/Dockerfile.graviton.cpu
  pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
  src/image_builder.py
  test/dlc_tests/sanity/test_pre_release.py
Labels: src, build, test, pytorch, sanity, Size:S

#3162 [test] Skip test_BYOC_training Training Compiler test on TF DLCs
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smtrcomp.py
Labels: test, Size:XS, sagemaker_tests

#3163 remove SM_TOOLKIT_VERSION arg from ec2 image build.
  pytorch/inference/buildspec-1-13.yml
  pytorch/inference/buildspec-eia.yml
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/buildspec.yml
Labels: build, pytorch, Size:XS

#3149 [PYTORCH][BUILD][NEURON][NEURONX][INFERENCE][TRAINING] Add Torch Neuron(x) images for SDK 2.11
  data/ignore_ids_safety_scan.json
  pytorch/inference/buildspec-1-13-neuron.yml
  pytorch/inference/buildspec-1-13-neuronx.yml
  pytorch/inference/buildspec-neuron.yml
  pytorch/inference/buildspec-neuronx.yml
  pytorch/inference/docker/1.13/py3/sdk2.11.0/Dockerfile.neuron
  pytorch/inference/docker/1.13/py3/sdk2.11.0/Dockerfile.neuron.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/sdk2.11.0/Dockerfile.neuronx
  pytorch/inference/docker/1.13/py3/sdk2.11.0/Dockerfile.neuronx.os_scan_allowlist.json
  pytorch/training/buildspec-1-13-neuronx.yml
  pytorch/training/buildspec-neuronx.yml
  pytorch/training/docker/1.13/py3/sdk2.11.0/Dockerfile.neuronx
  pytorch/training/docker/1.13/py3/sdk2.11.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/sanity/test_safety_check.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_neuron.py
  test/sagemaker_tests/pytorch/training/resources/neuron/all_reduce/all_reduce.py
  test/sagemaker_tests/pytorch/training/resources/neuron/all_reduce/entrypoint.py
  test/sagemaker_tests/pytorch/training/resources/neuron/mlp/entrypoint.py
  test/test_utils/__init__.py
Labels: build, test, pytorch, sanity, Size:S, sagemaker_tests

#3150 [TENSORFLOW][BUILD][NEURON][NEURONX][INFERENCE] Add Tensorflow Neuron(x) SDK 2.11.0 images
  data/ignore_ids_safety_scan.json
  tensorflow/inference/buildspec-2-10-neuron.yml
  tensorflow/inference/buildspec-2-10-neuronx.yml
  tensorflow/inference/buildspec-neuron.yml
  tensorflow/inference/buildspec-neuronx.yml
  tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.11.0/Dockerfile.neuron
  tensorflow/inference/docker/2.10/py3/sdk2.11.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.11.0/Dockerfile.neuronx
  tensorflow/inference/docker/2.10/py3/sdk2.11.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/test_utils/__init__.py
Labels: build, tensorflow, Size:S

#3167 [RELEASE] Release Pytorch Neuron(x) images
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3168 [RELEASE] Add Neuron(x) Tensorflow images for release and split Pytorch devices
  release_images_inference.yml
Labels: Size:S

#3170 [djl-serving] Release DJL 0.23.0 DeepSpeed 0.9.5 container
  release_images_inference.yml
Labels: Size:XS, Size:S

#3171 [djl-serving] Release DJL 0.23.0 FasterTransformers container
  release_images_inference.yml
Labels: Size:XS

#3176 [RELEASE][NEURON][NEURONX] Add new releases to available_images.md and cleanup release_images
  available_images.md
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3169 [djl-serving] Add container uris for DJL-23.0 release
  available_images.md
Labels: Size:S

#3179 [Tensorflow][Training][Release] TF 2.13 Training Release
  release_images_training.yml
Labels: Size:XS

#3180 [autogluon][build] AutoGluon 0.8.0 inference containers patch
  autogluon/inference/docker/0.8/py3/Dockerfile.cpu
  autogluon/inference/docker/0.8/py3/cu117/Dockerfile.gpu
Labels: build, Size:XS, autogluon

#3181 [AutoGluon] Release 0.8.2
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3182 [post-release] Add TF 2.13 to available images
  available_images.md
Labels: Size:XS, Size:S

#3183 [djl-serving] Deprecate DJL Serving 0.20.0 image
  available_images.md
Labels: Size:XS

#3185 [AutoGluon]0.8.2 post release
  available_images.md
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3166 Release HF PT 2.0 inference CPU GPU images
  release_images_inference.yml
Labels: Size:XS

#3198 [Documentation] | [Triton] Update documentation for Triton v23.05 release
  available_images.md
Labels: Size:XS

#3197 [AutoGluon] 0.7.0 image patching
  autogluon/inference/docker/0.7/py3/Dockerfile.cpu
  autogluon/inference/docker/0.7/py3/cu117/Dockerfile.gpu
  autogluon/training/docker/0.7/py3/Dockerfile.cpu
  autogluon/training/docker/0.7/py3/cu117/Dockerfile.gpu
Labels: build, Size:S, autogluon

#3189 [NEURON][NEURONX][PYTORCH][BUILD] Release images for Neuron SDK 2.12
  pytorch/inference/buildspec-1-13-neuron.yml
  pytorch/inference/buildspec-1-13-neuronx.yml
  pytorch/inference/buildspec-neuron.yml
  pytorch/inference/buildspec-neuronx.yml
  pytorch/inference/docker/1.13/py3/sdk2.12.0/Dockerfile.neuron
  pytorch/inference/docker/1.13/py3/sdk2.12.0/Dockerfile.neuron.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/sdk2.12.0/Dockerfile.neuronx
  pytorch/inference/docker/1.13/py3/sdk2.12.0/Dockerfile.neuronx.os_scan_allowlist.json
  pytorch/training/buildspec-1-13-neuronx.yml
  pytorch/training/buildspec-neuronx.yml
  pytorch/training/docker/1.13/py3/sdk2.12.0/Dockerfile.neuronx
  pytorch/training/docker/1.13/py3/sdk2.12.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/sanity/test_pre_release.py
  test/requirements.txt
  test/test_utils/__init__.py
Labels: build, test, pytorch, tensorflow, sanity, Size:S

#3202 [AutoGluon] 0.7 patch release
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3203 [PYTORCH][NEURON][RELEASE] Add Pytorch SDK 212 images to release_images.yml
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3206 [TENSORFLOW][NEURONX][NEURONX][BUILD] Build and release TF Neuron SDK 212 images
  data/ignore_ids_safety_scan.json
  tensorflow/inference/buildspec-2-10-neuron.yml
  tensorflow/inference/buildspec-2-10-neuronx.yml
  tensorflow/inference/buildspec-neuron.yml
  tensorflow/inference/buildspec-neuronx.yml
  tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.12.0/Dockerfile.neuron
  tensorflow/inference/docker/2.10/py3/sdk2.12.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.12.0/Dockerfile.neuronx
  tensorflow/inference/docker/2.10/py3/sdk2.12.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/sanity/test_pre_release.py
Labels: build, test, tensorflow, sanity, Size:S

#3205 [djl-serving] Release DJL 0.23.0 TNX Transformers container
  release_images_inference.yml
Labels: Size:XS

#3209 [RELEASE][NEURON][TENSORFLOW] Add Neuron Tensorflow inference images for SDK 2.12.0 to release
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3210 Add Neuron SDK 2.12.0 TF inference images to available_images.md
  available_images.md
  release_images_inference.yml
Labels: Size:S
