Repository aws/deep-learning-containers, pull requests merged in 2023-04, with the labels that each got.

#2820 [Tensorflow][Training]TF 2.11.1 Patch Release
  tensorflow/training/buildspec-2-11.yml
  tensorflow/training/docker/2.11/py3/Dockerfile.cpu
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.gpu
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
Labels: build, tensorflow, Size:S

#2840 Release TF 2.11.1 training DLC
  release_images_training.yml
Labels: Size:S

#2841 [Huggingface][Test] Fix Huggingface Canaries
  test/test_utils/__init__.py
Labels: Size:XS

#2663 [IMDSv2] Enforce IMDSv2 on EC2 instances
  test/dlc_tests/sanity/test_telemetry.py
  test/test_utils/ec2.py
Labels: build, test, mxnet, pytorch, tensorflow, sanity, Size:S

#2844 Stale PR Checker and Remover
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/stale_pr.yml
Labels: Size:S

#2836 [PyTorch][SageMager][x86_64][Graviton] PT 2.0 SM currency
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/buildspec.yml
  test/sagemaker_tests/pytorch/inference/integration/local/test_serving.py
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#2848 Add training EC2 DLCs to available image
  available_images.md
Labels: build, test, pytorch, ecs, sanity, Size:XS, Size:S, sagemaker_tests

#2847 [NEURON][ALL][BUILD] Make sure enabling neuron doesn't also enable neuronx
  dlc_developer_config.toml
  src/config.py
  src/image_builder.py
  src/main.py
Labels: src, Size:S

#2839 [NEURON][TF][BUILD] - Whitelist more Neuron TF 2.10.1 vulnerabilities
  tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.9.0/Dockerfile.neuron.os_scan_allowlist.json
Labels: build, tensorflow, Size:S

#2806 Add Neuron Tensorflow 1.15.5 SDK 2.8.0 release info
  available_images.md
Labels: Size:XS

#2842 Update HF TF images to TF 2.11.1
  huggingface/tensorflow/inference/buildspec.yml
  huggingface/tensorflow/inference/docker/2.11/py3/Dockerfile.cpu
  huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu
  huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:XS, Size:S

#2827 Fix bugs to enable SAGEMAKER_GUNICORN_WORKERS > 1 on MME.
  tensorflow/inference/docker/build_artifacts/sagemaker/multi_model_utils.py
  tensorflow/inference/docker/build_artifacts/sagemaker/python_service.py
  tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
  tensorflow/inference/docker/build_artifacts/sagemaker/tfs_utils.py
Labels: build, tensorflow, Size:S

#2854 Add Neuron Tensorflow 2.10.1 to release_images
  release_images_inference.yml
Labels: Size:XS

#2799 [huggingface_pytorch_inference] Add IPEx dependency in pytorch inference.
  huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu
  test/sagemaker_tests/huggingface/inference/integration/__init__.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_ipex_inference.py
  test/sagemaker_tests/huggingface/inference/resources/code/ipex_inference.py
Labels: build, test, huggingface, Size:XS, Size:S, sagemaker_tests

#2853 Release HF TF2.11.1 and HF PT 1.13
  release_images_inference.yml
Labels: Size:XS, Size:S

#2855 Add TF 2.10 Neuron inference image to available_images
  available_images.md
Labels: Size:XS

#2857 [BUILD][PT][NEURON] Add PT NeuronX release image to template
  .release_images_template.yml
  release_images_inference.yml
Labels: Size:XS

#2808 [NEURON][TF][BUILD] - Release TF 2.10 with neuronx SDK 2.9.0
  tensorflow/inference/buildspec-2-10-neuronx.yml
  tensorflow/inference/buildspec-neuronx.yml
  tensorflow/inference/docker/2.10/py3/sdk2.9.0/Dockerfile.neuronx
  tensorflow/inference/docker/2.10/py3/sdk2.9.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/neuron_tests/simple_x/1/keras_metadata.pb
  test/dlc_tests/container_tests/bin/neuron_tests/simple_x/1/saved_model.pb
  test/dlc_tests/container_tests/bin/neuron_tests/simple_x/1/variables/variables.data-00000-of-00001
  test/dlc_tests/container_tests/bin/neuron_tests/simple_x/1/variables/variables.index
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/dlc_tests/ecs/tensorflow/inference/test_ecs_tensorflow_inference.py
  test/dlc_tests/eks/eks_manifest_templates/pytorch/inference/single_node_neuronx_inference.yaml
  test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py
  test/dlc_tests/sanity/test_pre_release.py
  test/sagemaker_tests/pytorch/inference/conftest.py
  test/sagemaker_tests/tensorflow/inference/test/data/tfs-neuronx-model.tar.gz
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/test_tfs.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/util.py
  test/test_utils/__init__.py
  test/test_utils/ec2.py
Labels: build, test, tensorflow, ecs, eks, ec2, sanity, Size:S, sagemaker_tests

#2858 [BUILD][TF][NEURON] Add TF 2.10.1 NeuronX to releases
  release_images_inference.yml
Labels: Size:XS

#2859 [BUILD] Remove newly released NeuronX images from release_images_inference.yml
  .release_images_template.yml
  release_images_inference.yml
Labels: Size:S

#2856 [djlserving] Patch 0.21.0 images
  release_images_inference.yml
Labels: Size:S

#2863 [pytorch][release] Add PT 2.0 releases SM/EC2 x86_64/Graviton
  release_images_inference.yml
Labels: Size:S

#2864 DJL 0.21.0 deepspeed 0.8.3 release
  release_images_inference.yml
Labels: Size:S

#2865 [pytorch][release] Ddd PT 3.10 to release images test
  test/sagemaker_tests/pytorch/inference/conftest.py
Labels: test, Size:XS, sagemaker_tests

#2867 release DJL 0.21.0 fastertransformer 5.3.0
  release_images_inference.yml
Labels: Size:XS

#2868 update container image
  available_images.md
Labels: Size:XS

#2869 Release DJL 0.21.0 cpu full
  release_images_inference.yml
Labels: Size:XS

#2845 [pytorch][build][test]Patch PyTorch Inference 1.12
  data/ignore_ids_safety_scan.json
  pytorch/inference/docker/1.12/py3/Dockerfile.cpu
  pytorch/inference/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.gpu
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.gpu
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, test, pytorch, sanity, Size:XS, Size:S

#2850 [pytorch][graviton] Update TS and SM-Toolkit
  data/ignore_ids_safety_scan.json
  pytorch/inference/docker/1.12/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/Dockerfile.graviton.cpu
  pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json
  src/utils.py
Labels: src, build, pytorch, Size:XS, Size:S

#2851 Adding upgrade kubeflow to the list of EKS operations
  eks_infrastructure/build.sh
  eks_infrastructure/build_param.json
  eks_infrastructure/build_param.template
  eks_infrastructure/upgrade_kubeflow.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
Labels: test, eks, Size:S

#2872 release TF2.12 images
  .release_images_template.yml
  release_images_training.yml
Labels: Size:S

#2860 Add NeuronX releases and fix table formatting for Neuron
  available_images.md
Labels: Size:XS

#2875 [pytorch] Update Available Images for PyTorch 2.0 SageMaker Inference Images
  available_images.md
Labels: Size:XS

#2874 Change the order of deleting kubeflow manifest
  eks_infrastructure/install_cluster_components.sh
  eks_infrastructure/upgrade_kubeflow.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
Labels: test, eks, Size:XS, Size:S

#2878 [Tensorflow] Update available_images.md for Tensorflow Inference
  available_images.md
Labels: Size:XS

#2866 Increase Operations Per Run for Stale Check
  .github/workflows/stale_pr.yml
Labels: Size:XS

#2879 add pt1.13.1 and pt1.12.1 graviton patch release
  release_images_inference.yml
Labels: Size:S

#2884 remove kubeflow namespace uninstallation step
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
Labels: test, eks, Size:XS

#2886 Add PT-1.13.1 training EC2 to prior available images
  available_images.md
Labels: build, test, pytorch, ecs, ec2, benchmark, sanity, Size:XS, Size:S, sagemaker_tests

#2887 Upgrade mxnet pr cluster
  eks_infrastructure/build_param.json
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
Labels: test, eks, Size:XS

#2888 Upgrade manifest for pytorch and tensorflow
  eks_infrastructure/build_param.json
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
Labels: test, eks, Size:XS

#2889 Create new EKS mxnet clusters
  eks_infrastructure/build_param.json
Labels: Size:XS

#2880 Bump HF TF version to 2.11.1 in available images
  available_images.md
Labels: Size:XS

#2892 build: add release specs for PT2.0 tr
  .release_images_template.yml
  release_images_training.yml
Labels: Size:S

#2891 Add formatting checks to DLC repo
  .git-blame-ignore-revs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  pyproject.toml
  test/dlc_tests/sanity/quick_checks/test_formatting_and_linting.py
Labels: test, sanity, Size:S

#2897 Add logs to ec2 test execution
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/test_utils/ec2.py
Labels: test, ec2, Size:S

#2900 [pytorch] PT 2.0 GPU patch release
  release_images_inference.yml
Labels: Size:S

#2876 [tensorflow][graviton] TensorFlow Serving 2.9.1 Graviton patch testing
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
Labels: test, ec2, Size:XS

#2905 [Doc] | [Triton] | Upgrade doc to mention Triton v23.02 and v23.03
  available_images.md
Labels: Size:XS

#2909 [tensorflow][release] TFS 2.9.1 Graviton patch-release
  release_images_inference.yml
Labels: Size:S

#2913 doc: update the image list for PT2.0 training
  available_images.md
Labels: Size:XS

#2916 Add github action for formatting
  .github/workflows/black.yml
  eks_infrastructure/eks_cleanup/eks_cleanup_job.py
  generate_dlc_image_release_information.py
  release/dlc_release_information.py
  src/image.py
  src/metrics.py
  src/output.py
  src/requirements.txt
  src/safety_report_generator.py
  test/dlc_tests/benchmark/sagemaker/tensorflow/training/resources/clm/run_clm.py
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/benchmark/tf1_serving_perf.py
  test/dlc_tests/container_tests/bin/benchmark/tf2_serving_perf.py
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/eks/mxnet/inference/test_eks_mxnet_inference.py
  test/dlc_tests/eks/mxnet/training/test_eks_mxnet_multinode_training.py
  test/dlc_tests/eks/mxnet/training/test_eks_mxnet_training.py
  test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
  test/dlc_tests/sanity/test_telemetry.py
  test/sagemaker_tests/huggingface/inference/integration/local/test_serving.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/local/test_single_machine_training.py
  test/sagemaker_tests/huggingface_pytorch/training/resources/scripts/train.py
  test/sagemaker_tests/huggingface_tensorflow/training/resources/local_scripts/train.py
  test/sagemaker_tests/huggingface_tensorflow/training/resources/scripts/train.py
  test/sagemaker_tests/mxnet/inference/resources/neuron_handlers/model/code/mnist-neuron.py
  test/sagemaker_tests/mxnet/training/conftest.py
  test/sagemaker_tests/mxnet/training/resources/mnist/horovod_mnist.py
  test/sagemaker_tests/pytorch/inference/resources/resnet/model_neuron/code/resnet18.py
  test/sagemaker_tests/pytorch/inference/resources/resnet/model_neuronx/code/resnet18.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/data_pipeline.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/fp16/fp16.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/fp16/loss_scaler.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/fp16/megatron/clip_grads.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/fp16/megatron/fp16.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/fp16/megatron/grad_scaler.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/learning_rates.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/memory_tracker.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/train_gpt_simple.py
  test/sagemaker_tests/pytorch/training/resources/mnist/smdebug_mnist.py
  test/sagemaker_tests/pytorch/training/resources/neuron/mlp/model.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/test_tfs.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/util.py
  test/sagemaker_tests/tensorflow/tensorflow1_training/integration/local/test_training.py
  test/sagemaker_tests/tensorflow/tensorflow1_training/resources/keras_inception.py
  test/sagemaker_tests/tensorflow/tensorflow1_training/resources/mnist/horovod_mnist.py
  test/sagemaker_tests/tensorflow/tensorflow1_training/resources/mnist/mnist.py
  test/sagemaker_tests/tensorflow/tensorflow1_training/resources/mnist/tf1x_mnist_smdebug.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/local/test_training.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/resources/keras_inception.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/resources/mnist/mnist.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/resources/mnist/mnist_custom.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/resources/mnist/mnist_smdebug.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/resources/smmodelparallel/tf2_checkpoint_test.py
  test/test_utils/ec2.py
  test/test_utils/ecs.py
  test/test_utils/eks.py
  test/test_utils/pytest_cache.py
Labels: src, test, eks, ec2, benchmark, sanity, Size:XS, Size:S, sagemaker_tests

#2918 Rely only on github actions for formatting
  .git-blame-ignore-revs
  .github/workflows/black.yml
  test/dlc_tests/sanity/quick_checks/test_formatting_and_linting.py
Labels: src, test, sanity, Size:S

#2919 Remove pytorch inference toolkit from HF PT images
  huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
Labels: build, huggingface, Size:XS

#2903 [PT-1.13] Upgrade SMModelParallel in Training SM DLC, Fix PT2.0 breaking changes
  pytorch/training/buildspec-1-13.yml
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/pytorch_tests/0001-test-adapt-BERT_pytorch-training-with-gloo-mpi-backend.patch
  test/dlc_tests/container_tests/bin/pytorch_tests/0001-test-add-flag-for-inductor-in-ddp.patch
  test/dlc_tests/container_tests/bin/pytorch_tests/installOSSPyTorch
  test/dlc_tests/container_tests/bin/pytorch_tests/setupPyTorchBackendTest
  test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVD
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchNccl
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_dgl_inductor.py
Labels: src, build, test, pytorch, eks, ec2, benchmark, sanity, Size:S, sagemaker_tests

#2915 [NEURON][TF][BUILD] Add PT 1.13.0 training with Neuron SDK 2.9.1
  dlc_developer_config.toml
  pytorch/training/buildspec-1-13-neuronx.yml
  pytorch/training/buildspec-neuronx.yml
  pytorch/training/docker/1.13/py3/sdk2.9.1/Dockerfile.neuronx
  pytorch/training/docker/1.13/py3/sdk2.9.1/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ecs/conftest.py
  test/dlc_tests/ecs/pytorch/training/test_ecs_pytorch_training.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/dlc_tests/sanity/test_pre_release.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_neuron_hosting.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_neuron.py
  test/test_utils/__init__.py
Labels: build, test, pytorch, ecs, ec2, sanity, Size:S, sagemaker_tests

#2925 Release Torch 1.13.0 NeuronX training image with SDK 2.9.1
  release_images_training.yml
Labels: Size:XS

#2929 [Tensorflow][Test] Fix parse_canary method for TF2.12 images
  test/test_utils/__init__.py
Labels: Size:XS

#2928 Add Pytorch Training with Neuron SDK 2.9.1 to available images
  available_images.md
  release_images_training.yml
Labels: Size:XS

#2922 patch PT-1.13 SM Training for breaking changes from PT2.0
  pytorch/training/buildspec-1-13.yml
  pytorch/training/docker/1.13/py3/Dockerfile.cpu
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  test/dlc_tests/benchmark/ec2/pytorch/training/test_performance_pytorch_training.py
  test/dlc_tests/benchmark/sagemaker/pytorch/training/test_performance_inductor.py
  test/sagemaker_tests/pytorch/training/resources/gpt2/train_gpt_simple.py
Labels: build, test, pytorch, benchmark, Size:S, sagemaker_tests

#2926 [TESTING][NEURON][TF/TORCH][INFERENCE] Add inf2 testing for NeuronX inference images and mark them as inf2-compatible
  available_images.md
  pytorch/inference/docker/1.13/py3/sdk2.9.0/Dockerfile.neuronx
  pytorch/inference/docker/1.13/py3/sdk2.9.0/Dockerfile.neuronx.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.9.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/dlc_tests/ecs/pytorch/inference/test_ecs_pytorch_inference.py
  test/dlc_tests/ecs/tensorflow/inference/test_ecs_tensorflow_inference.py
  test/sagemaker_tests/pytorch/inference/conftest.py
Labels: build, test, pytorch, tensorflow, ecs, ec2, Size:S, sagemaker_tests

#2934 Add DJL neuron release yaml config
  release_images_inference.yml
Labels: Size:XS

#2936 [test] Temporarily disable pytest failure remote caching
  src/requirements.txt
  test/requirements.txt
  test/sagemaker_tests/autogluon/inference/requirements.txt
  test/sagemaker_tests/autogluon/training/requirements.txt
  test/sagemaker_tests/huggingface/inference/requirements.txt
  test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
  test/sagemaker_tests/huggingface_tensorflow/training/requirements.txt
  test/sagemaker_tests/mxnet/inference/requirements.txt
  test/sagemaker_tests/mxnet/training/requirements.txt
  test/sagemaker_tests/pytorch/inference/requirements.txt
  test/sagemaker_tests/pytorch/training/requirements.txt
  test/sagemaker_tests/tensorflow/inference/requirements.txt
  test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt
  test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt
  test/test_utils/pytest_cache.py
Labels: src, test, Size:XS, Size:S, sagemaker_tests
