Repository aws/deep-learning-containers, pull requests merged in 2023-11, with the labels that each got.

#3454 [dgl] Add team marker for dgl tests
  test/dlc_tests/ec2/mxnet/training/test_mxnet_training.py
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ecs/mxnet/training/test_ecs_mxnet_training.py
  test/dlc_tests/ecs/pytorch/training/test_ecs_pytorch_training.py
  test/dlc_tests/eks/mxnet/training/test_eks_mxnet_training.py
  test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
  test/sagemaker_tests/mxnet/training/integration/sagemaker/test_dgl.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_dgl.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_dgl_inductor.py
Labels: test, ecs, eks, ec2, Size:XS, sagemaker_tests

#3408 [HF/SAI] Add team marker for huggingface/SAI test
  test/sagemaker_tests/huggingface/inference/integration/local/test_serving.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_diffusers_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_hub_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_ipex_inference.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_neuron_hosting.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_neuronx_decoder_hosting.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_neuronx_encoder_hosting.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_neuronx_sdxl_hosting.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_sm_trained_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_speech_model.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_torch_compile.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_vision_model.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/local/test_single_machine_training.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/local/test_trcomp.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_diffusers.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_neuronx.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_smdp.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_smmp.py
  test/sagemaker_tests/huggingface_tensorflow/training/integration/local/test_placeholder.py
  test/sagemaker_tests/huggingface_tensorflow/training/integration/sagemaker/test_smdataparallel.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_stabilityai.py
Labels: test, Size:S, sagemaker_tests

#3472 Skip tests for non compatible images on P5
  test/dlc_tests/conftest.py
  test/sagemaker_tests/autogluon/training/conftest.py
  test/sagemaker_tests/autogluon/training/integration/__init__.py
  test/sagemaker_tests/huggingface_pytorch/training/conftest.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/__init__.py
  test/sagemaker_tests/huggingface_tensorflow/training/integration/__init__.py
  test/sagemaker_tests/huggingface_tensorflow/training/integration/conftest.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/__init__.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py
Labels: test, ec2, Size:S, sagemaker_tests

#3481 [PyTorch][Sagemaker][Training] skip efa healthcheck for pt2.1
  test/dlc_tests/ec2/test_efa.py
Labels: test, ec2, Size:XS

#3480 Release HF PT neuronx 1.13.1
  release_images_inference.yml
Labels: Size:XS

#3478 [huggingface_pytorch_neuronx] Training - update for Transformers to 4.34.1 - Neuron sdk 2.15
  huggingface/pytorch/training/buildspec-neuronx.yml
  huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_neuronx.py
Labels: build, test, huggingface, Size:S, sagemaker_tests

#3486 Release SM DLC PT2.0.1 CUDA121
  release_images_training.yml
Labels: Size:XS

#3487 [djl-serving] patch for djl-pytorch-inf2
  release_images_inference.yml
Labels: Size:XS

#3489 release HF PT Neuronx training image
  release_images_training.yml
Labels: Size:XS

#3493 Add Pytorch Neuron(X) SDK 2.15.0 images to release
  release_images_inference.yml
Labels: Size:S

#3492 Reset PT2 SM Training Buildspec to build default images
  pytorch/training/buildspec-2-0-sm.yml
Labels: build, pytorch, Size:S

#3495 Add Pytorch Neuron(X) SDK 2.15 inference images to release_images.md
  available_images.md
  release_images_inference.yml
Labels: Size:S

#3473 fix: Removing libwebp6 and adding security upgrades in SAI images
  stabilityai/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: Size:XS, Size:S

#3490 PT2.1 SM Training availble_image.md
  available_images.md
Labels: Size:XS

#3496 update HF PT neuronx training/inference image doc
  available_images.md
Labels: Size:XS

#3500 Update EKS nodegroups for PT and TF
  eks_infrastructure/build_param.json
Labels: test, ec2, Size:XS

#3503 Add PT 2.0.1 to inference release yml
  release_images_inference.yml
Labels: Size:S

#3508 set cuda_home flag for Tensorflow EFA test
  test/dlc_tests/ec2/test_efa.py
Labels: test, ec2, Size:XS

#3516 remove habana dependency from test initialization
  test/test_utils/__init__.py
Labels: Size:XS

#3518 Clear out release yaml files
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3519 disable ec2 training builds for TF 2.13
  tensorflow/training/buildspec.yml
Labels: build, tensorflow, Size:S

#3522 release TF2.12 and TF2.13 SM images
  release_images_training.yml
Labels: Size:S

#3441 [test][deep_canary] Add logic to execute DLC Deep Canary tests
  deep_canary_buildspec.yml
  dlc_developer_config.toml
  src/config.py
  src/main.py
  src/start_testbuilds.py
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/dlc_tests/sanity/test_canary_integration.py
  test/test_utils/__init__.py
  test/test_utils/ec2.py
  test/testrunner.py
Labels: src, test, ec2, sanity, Size:S

#3511 Automate EKS Host Patching
  eks_infrastructure/build.sh
  eks_infrastructure/build_param.template
  eks_infrastructure/helper.sh
  eks_infrastructure/host_patching_buildspec.yml
  eks_infrastructure/patch_hosts.json
  eks_infrastructure/patch_hosts.sh
  eks_infrastructure/patch_hosts.template
Labels: Size:S

#3477 Add team marker for tensorflow/mxnet test
  test/dlc_tests/benchmark/ec2/mxnet/test_performance_mxnet_inference.py
  test/dlc_tests/benchmark/ec2/mxnet/test_performance_mxnet_training.py
  test/dlc_tests/benchmark/ec2/tensorflow/inference/test_performance_tensorflow_inference.py
  test/dlc_tests/benchmark/ec2/tensorflow/training/test_performance_tensorflow_training.py
  test/dlc_tests/benchmark/sagemaker/mxnet/training/test_performance_mxnet_sm_training.py
  test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_performance_tensorflow_sm_training.py
  test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py
  test/dlc_tests/ec2/mxnet/training/test_mxnet_training.py
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py
  test/dlc_tests/ec2/test_curand.py
  test/dlc_tests/ec2/test_efa.py
  test/dlc_tests/ecs/mxnet/inference/test_ecs_mxnet_inference.py
  test/dlc_tests/ecs/mxnet/training/test_ecs_mxnet_training.py
  test/dlc_tests/ecs/tensorflow/inference/test_ecs_tensorflow_inference.py
  test/dlc_tests/ecs/tensorflow/training/test_ecs_tensorflow_training.py
  test/dlc_tests/eks/mxnet/inference/test_eks_mxnet_inference.py
  test/dlc_tests/eks/mxnet/training/test_eks_mxnet_multinode_training.py
  test/dlc_tests/eks/mxnet/training/test_eks_mxnet_training.py
  test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py
  test/dlc_tests/eks/tensorflow/training/test_eks_tensorflow_multi_node_training.py
  test/dlc_tests/eks/tensorflow/training/test_eks_tensorflow_training.py
  test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_batch_transform.py
  test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_gluonnlp.py
  test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_hosting.py
  test/sagemaker_tests/mxnet/training/integration/sagemaker/test_gluonnlp.py
  test/sagemaker_tests/mxnet/training/integration/sagemaker/test_horovod.py
  test/sagemaker_tests/mxnet/training/integration/sagemaker/test_training.py
  test/sagemaker_tests/mxnet/training/integration/sagemaker/test_tuning.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/test_tfs.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_experiments.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_horovod.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_pipemode.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_tuning_model_dir.py
Labels: test, ecs, eks, ec2, benchmark, Size:S, sagemaker_tests

#3517 fix: Huggingface Tensorflow Inference CVEs
  data/ignore_ids_safety_scan.json
  huggingface/tensorflow/inference/docker/2.11/py3/Dockerfile.cpu
  huggingface/tensorflow/inference/docker/2.11/py3/Dockerfile.cpu.os_scan_allowlist.json
  huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu
  huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
  huggingface/tensorflow/training/docker/2.11/py3/cu112/Dockerfile.gpu
Labels: build, huggingface, Size:S

#3527 Release buildspec install requirements
  release_buildspec.yml
Labels: Size:XS

#3465 [BUILD][TENSORFLOW][NEURON(X)][INFERENCE] Add Tensorflow Neuron SDK 2.15.0 images
  data/ignore_ids_safety_scan.json
  src/safety_report_generator.py
  tensorflow/inference/buildspec-2-10-neuron.yml
  tensorflow/inference/buildspec-2-10-neuronx.yml
  tensorflow/inference/buildspec-neuron.yml
  tensorflow/inference/buildspec-neuronx.yml
  tensorflow/inference/buildspec-tf1-neuron.yml
  tensorflow/inference/docker/1.15/py3/sdk2.15.1/Dockerfile.neuron
  tensorflow/inference/docker/1.15/py3/sdk2.15.1/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.15.1/Dockerfile.neuron
  tensorflow/inference/docker/2.10/py3/sdk2.15.1/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.15.1/Dockerfile.neuronx
  tensorflow/inference/docker/2.10/py3/sdk2.15.1/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/sanity/test_pre_release.py
  test/dlc_tests/sanity/test_safety_report_file.py
Labels: src, build, test, tensorflow, sanity, Size:S

#3521 TGI Available Images Cleanup
  available_images.md
Labels: Size:XS

#3530 Add Tensorflow SDK 2.15.1 images to release_images
  release_images_inference.yml
Labels: Size:S

#3531 fix: Adding HF TF release images
  release_images_inference.yml
Labels: Size:S

#3536 Updating availability zones to reflect capacity changes
  test/dlc_tests/conftest.py
Labels: Size:XS

#3537 Fix to test configuration to allow for searching for deprecated AMI's.
  test/test_utils/__init__.py
Labels: Size:XS

#3538 Adding list to track regional availability of p5 instances.
  test/sagemaker_tests/pytorch/training/conftest.py
Labels: test, Size:XS, sagemaker_tests

#3539 Skip smmp tests for p5 instances
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/__init__.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
Labels: test, Size:XS, Size:S, sagemaker_tests

#3541 Fix broken tests
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
Labels: test, Size:XS, Size:S, sagemaker_tests

#3543 [djl-serving] Add release images for djl-serving 0.25.0 and remove 0.…
  available_images.md
Labels: Size:S

#3544 Updating SM training fixtures
  test/sagemaker_tests/pytorch/training/conftest.py
Labels: test, Size:S, sagemaker_tests

#3545 [Build][Test] Check build issues
  src/requirements.txt
  test/requirements.txt
Labels: src, Size:XS

#3515 Add SM Profiler for TF 2.12, TF 2.13, PT 2.0
  pytorch/training/buildspec-2-0-sm.yml
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.gpu
  tensorflow/training/docker/2.12/py3/cu118/Dockerfile.gpu
  tensorflow/training/docker/2.13/py3/cu118/Dockerfile.gpu
  test/sagemaker_tests/pytorch/training/integration/local/test_smppy_local.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smppy.py
  test/sagemaker_tests/pytorch/training/resources/mnist/smppy_mnist.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/local/test_smppy_local.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smppy.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/resources/mnist/mnist_smppy.py
Labels: build, test, pytorch, tensorflow, Size:S, sagemaker_tests
