Repository aws/deep-learning-containers, pull requests merged in 2023-06, with the labels that each got.

#3056 [test] Fix coverage test on quick-check
  test/sagemaker_tests/autogluon/inference/requirements.txt
  test/sagemaker_tests/autogluon/training/requirements.txt
  test/sagemaker_tests/huggingface/inference/requirements.txt
  test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
  test/sagemaker_tests/huggingface_tensorflow/training/requirements.txt
  test/sagemaker_tests/mxnet/inference/requirements.txt
  test/sagemaker_tests/mxnet/training/requirements.txt
  test/sagemaker_tests/pytorch/inference/requirements.txt
  test/sagemaker_tests/pytorch/training/requirements.txt
  test/sagemaker_tests/tensorflow/inference/requirements.txt
  test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt
  test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt
  test/test_utils/test_reporting.py
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#2970 [test][ec2] Add EC2 EFA tests for Training DLCs
  dlc_developer_config.toml
  pytorch/training/docker/1.13/py3/Dockerfile.cpu
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  src/config.py
  src/start_testbuilds.py
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/efa/build_all_reduce_perf.sh
  test/dlc_tests/container_tests/bin/efa/efa_test.sh
  test/dlc_tests/container_tests/bin/efa/testEFA
  test/dlc_tests/container_tests/bin/efa/testEFASanity
  test/dlc_tests/ec2/test_efa.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/test_utils/__init__.py
  test/test_utils/ec2.py
  test/testrunner.py
Labels: src, build, test, pytorch, ec2, sanity, Size:S

#3043 [pytorch] Build/Test PT 2.0.1 x86/Graviton
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  pytorch/inference/docker/2.0/py3/Dockerfile.graviton.cpu
  pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_neuron_hosting.py
Labels: build, test, pytorch, Size:S, sagemaker_tests

#3059 [test][ecs] Fix bug that causes ecs_client creation failure
  test/dlc_tests/ecs/conftest.py
Labels: test, ecs, Size:XS

#3060 [test] Prevent infinite loop when finding repo path
  test/dlc_tests/sanity/quick_checks/test_buildspecs.py
  test/dlc_tests/sanity/quick_checks/test_yml_config.py
Labels: test, sanity, Size:XS

#3064 [pytorch][release] release PT 2.0.1 Inference x86/graviton
  release_images_inference.yml
Labels: Size:S

#3066 release images cleanup and update availalbe images
  available_images.md
  release_images_inference.yml
Labels: Size:S

#3070 Update release_images_inference.yml
  release_images_inference.yml
Labels: Size:XS

#3068 Add HF PT TGI 0.8.2 release definition
  release_images_inference.yml
Labels: Size:XS, Size:S

#3071 Update HF TGI DLC version
  .github/CODEOWNERS
  available_images.md
Labels: Size:XS

#3051 [EC2 DLC PyTorch] Update PT from 2.0.0 to 2.0.1
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/Dockerfile.cpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  test/dlc_tests/sanity/test_utility_installation.py
Labels: build, test, pytorch, sanity, Size:S

#2981 [test] SM Remote function tests
  test/dlc_tests/container_tests/bin/test_remote_function.py
  test/dlc_tests/sanity/test_remote_function_compatibility.py
Labels: test, sanity, Size:S

#3079 [DLC] Add LMI V4.5: DeepSpeed container update
  release_images_inference.yml
Labels: Size:XS

#3078 [test][ec2] Fix EFA test for p3dn instances
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/efa/testEFA
  test/test_utils/ec2.py
Labels: test, ec2, Size:XS, Size:S

#3088 [djlserving] patch fastertransformers 0.22.1 image
  release_images_inference.yml
Labels: Size:XS

#3090 Release PT 1.13 EC2 and SM
  release_images_inference.yml
Labels: Size:S

#3074 [test][sagemaker] Add instance exception for il-central-1
  available_images.md
  test/sagemaker_tests/__init__.py
  test/sagemaker_tests/autogluon/inference/conftest.py
  test/sagemaker_tests/autogluon/training/conftest.py
  test/sagemaker_tests/huggingface/inference/conftest.py
  test/sagemaker_tests/huggingface_pytorch/training/conftest.py
  test/sagemaker_tests/huggingface_tensorflow/training/integration/__init__.py
  test/sagemaker_tests/mxnet/inference/integration/__init__.py
  test/sagemaker_tests/mxnet/training/integration/__init__.py
  test/sagemaker_tests/pytorch/inference/conftest.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/pytorch/training/utils/image_utils.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
  test/sagemaker_tests/tensorflow/tensorflow1_training/integration/__init__.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py
  test/test_utils/__init__.py
  test/test_utils/imageutils.py
Labels: test, Size:S, sagemaker_tests

#3075 Folder Structure for Stability
  dlc_developer_config.toml
  src/constants.py
  stabilityai/pytorch/inference/buildspec.yml
  stabilityai/pytorch/training/buildspec.yml
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/dlc_tests/sanity/test_pre_release.py
  test/dlc_tests/sanity/test_telemetry.py
  test/test_utils/__init__.py
Labels: src, build, test, pytorch, sanity, Size:S

#3097 [PyTorch][Inference] Add wait to check CloudWatch logs
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
Labels: test, Size:XS, sagemaker_tests

#3093 [Test] Add tests for Stability
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
  test/sagemaker_tests/pytorch/inference/conftest.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_neuron_hosting.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_stabilityai.py
  test/test_utils/sagemaker.py
Labels: test, ec2, sanity, Size:XS, Size:S, sagemaker_tests

#3100 [Update Available Images] PT2.0.1
  available_images.md
Labels: Size:XS

#3099 [Release][Inference] PyTorch 2.0.1
  release_images_inference.yml
Labels: Size:S

#3083 upgrade deepspeed container
  available_images.md
Labels: Size:XS

#3101 Add lookup fixtures to run specific stabilityAI tests
  test/dlc_tests/conftest.py
Labels: test, ec2, Size:XS, Size:S

#3098 [djl-serving] cve patching lmi containers
  release_images_inference.yml
Labels: Size:S

#3091 [autogluon][build] AutoGluon 0.7.0 inference containers v2 - change to torch-serve
  autogluon/build_artifacts/inference/config.properties
  autogluon/build_artifacts/inference/torchserve-entrypoint.py
  autogluon/inference/buildspec.yml
  autogluon/inference/docker/0.7/py3/Dockerfile.cpu
  autogluon/inference/docker/0.7/py3/cu117/Dockerfile.gpu
  test/dlc_tests/sanity/test_dlc_labels.py
Labels: build, test, sanity, Size:S, autogluon

#3106 [djl-serving] cve patch on 0.21.0 cpu lmi container
  release_images_inference.yml
Labels: Size:XS, Size:S

#3113 [Test] Regex solution for getting image tag
  test/dlc_tests/sanity/test_pre_release.py
Labels: test, sanity, Size:XS

#3107 [djl-serving] cve patch on 0.21.0 fastertransformer lmi container
  release_images_inference.yml
Labels: Size:XS, Size:S

#3111 [autogluon][build] AutoGluon 0.7.0 inference containers v2 - fixes
  autogluon/inference/docker/0.7/py3/Dockerfile.cpu
  autogluon/inference/docker/0.7/py3/cu117/Dockerfile.gpu
Labels: build, Size:XS, Size:S, autogluon

#3117 release autogluon v0.7 inference DLC
  release_images_inference.yml
Labels: Size:XS

#3127 [djl] Update djl deepspeed images for cve patches
  release_images_inference.yml
Labels: Size:S

#3131 [djl] Update djl cpu images for cves
  release_images_inference.yml
Labels: Size:S

#3085 Add gdrcopy support in pt 1.13.1
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/gdrcopy/test_gdrcopy.sh
  test/dlc_tests/ec2/test_gdrcopy.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_gdrcopy.py
  test/sagemaker_tests/pytorch/training/resources/gdrcopy/test_gdrcopy.sh
  test/test_utils/__init__.py
  test/test_utils/ec2.py
Labels: build, test, pytorch, ec2, Size:S, sagemaker_tests

#3126 Add gdrcopy support in pt 2.0
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, test, pytorch, ec2, Size:XS, Size:S, sagemaker_tests

#3130 [HuggingFace] Add diffusers support to PT 1.13 INF DLC
  huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_torch_compile.py
Labels: build, test, huggingface, Size:XS, Size:S, sagemaker_tests

#3133 [djl] Update djl neuronx images for cves
  release_images_inference.yml
Labels: Size:XS

#3136 [djl] Update djl fastertransformer containers for cves
  release_images_inference.yml
Labels: Size:S

#3139 [HugginFace] Remove Installation Piece for HF Inference
  test/test_utils/__init__.py
Labels: Size:XS
