Repository aws/deep-learning-containers, pull requests merged in 2023-09, with the labels that each got.

#3301 [Release] EC2 PT2.0.1 CUDA121 Supporting P5 EC2 instance
  release_images_training.yml
Labels: Size:XS

#3308 [Available Images] P5 EC2 image PT2.0.1 CUDA12.1
  available_images.md
Labels: Size:XS

#3280 [build][test] Find buildspec for tests through artifact or env
  src/start_testbuilds.py
  test/dlc_tests/sanity/test_pre_release.py
  test/test_utils/__init__.py
Labels: src, test, sanity, Size:S

#3306 [PT2.0.1][CUDA12] remove ssh keys
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.gpu
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
Labels: build, pytorch, Size:S

#3304 [PyTorch] [SM, EC2] Upgrade torchserve version from 0.8.1 to 0.8.2
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/2.0/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/2.0/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/2.0/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/2.0/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
Labels: build, pytorch, Size:XS, Size:S

#3316 [PyTorch][Graviton][SM, EC2] Upgrade torchserve version from 0.8.1 to 0.8.2
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/docker/2.0/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json
  pytorch/inference/docker/2.0/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json
Labels: build, pytorch, Size:S

#3314 [BUILD][NEURON][NEURONX][TENSORFLOW] Add Tensorflow inference images for Neuron release 2.13.2
  data/ignore_ids_safety_scan.json
  tensorflow/inference/buildspec-2-10-neuron.yml
  tensorflow/inference/buildspec-2-10-neuronx.yml
  tensorflow/inference/buildspec-neuron.yml
  tensorflow/inference/buildspec-neuronx.yml
  tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.13.2/Dockerfile.neuron
  tensorflow/inference/docker/2.10/py3/sdk2.13.2/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.13.2/Dockerfile.neuronx
  tensorflow/inference/docker/2.10/py3/sdk2.13.2/Dockerfile.neuronx.os_scan_allowlist.json
Labels: build, tensorflow, Size:S

#3319 Add Neuron 2.13.2 Tensorflow images to release_images
  release_images_inference.yml
Labels: Size:S

#3318 [PyTorch] [SM, EC2] Add release image definitions for PT 2.0.1 inference torchserve upgrade
  release_images_inference.yml
Labels: Size:S

#3323 Release TGI 1.0.3
  release_images_inference.yml
Labels: Size:XS

#3313 [BUILD][NEURON][NEURONX][PYTORCH] Add Pytorch inf/training images for release 2.13.2
  pytorch/inference/buildspec-1-13-neuron.yml
  pytorch/inference/buildspec-1-13-neuronx.yml
  pytorch/inference/buildspec-neuron.yml
  pytorch/inference/buildspec-neuronx.yml
  pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuron
  pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuron.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx
  pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx.os_scan_allowlist.json
  pytorch/training/buildspec-1-13-neuronx.yml
  pytorch/training/buildspec-neuronx.yml
  pytorch/training/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx
  pytorch/training/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx.os_scan_allowlist.json
  test/dlc_tests/sanity/test_pre_release.py
  test/test_utils/__init__.py
Labels: build, test, pytorch, sanity, Size:S

#3325 Update release_images_inference.yml
  release_images_inference.yml
Labels: Size:XS, Size:S

#3321 Add Neuron 2.13.2 Pytorch images to release_images
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#3330 Update release_images_inference.yml with pytorch neuron 2.13.2
  release_images_inference.yml
Labels: Size:S

#3286 TGI 1.0.3 Available Image
  available_images.md
Labels: Size:XS

#3333 Update release_images_inference.yml
  available_images.md
  release_images_inference.yml
Labels: Size:S

#3334 [Tensorflow][Neuron] Remove TF2.10.1 Neuron Images from Release Images
  release_images_inference.yml
Labels: Size:S

#3320 Add Neuron 2.13.2 Tensorflow releases to available_images
  available_images.md
Labels: Size:XS, Size:S

#3331 [PT20 CUDA121] Speed up Apex, reduce image size, update aws ofi nccl plugin
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.gpu
Labels: build, pytorch, Size:S

#3336 [Release PT2.0 CUDA121] EC2 GPU training
  release_images_training.yml
Labels: Size:S

#3339 [PT20 CUDA121] Update available image
  available_images.md
Labels: Size:XS

#3337 [PT2.0+CUDA118] [Training GPU] Reduce Image size
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  test/dlc_tests/sanity/test_utility_installation.py
Labels: build, test, pytorch, sanity, Size:S

#3338 [Documentation] |[Triton] | Update available images with Triton v23.07 release
  available_images.md
Labels: Size:XS

#3343 [PT2.0 CUDA118] Just build ec2 images
  pytorch/training/buildspec.yml
Labels: build, pytorch, Size:S

#3346 [PT2.0 CUDA118] Build SM DLC
  pytorch/training/buildspec.yml
Labels: build, pytorch, Size:S

#3345 [stabilityai_pytorch] [inference] fix problem extracting non-gzip tar…
  stabilityai/pytorch/inference/docker/build_artifacts/torchserve-stabilityai-entrypoint.py
Labels: Size:XS

#3347 [Release] PT2.0 CUDA118 EC2 and SM
  release_images_training.yml
Labels: Size:S

#3349 Upgrade libwebp6 in SAI images
  stabilityai/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: Size:XS

#3315 Add TransformerEngine to PT 2.0 training images
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.gpu
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/transformerengine/testPTTransformerEngine
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ec2/test_transformerengine.py
Labels: build, test, pytorch, ec2, Size:S

#3352 Fast follow improvements for TE test experience
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.gpu
  test/dlc_tests/ec2/test_efa.py
  test/dlc_tests/ec2/test_transformerengine.py
Labels: build, test, pytorch, ec2, Size:S

#3293 [Pytorch][SM] Add health check required packages
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/healthcheck_tests/dcgm_test.sh
  test/dlc_tests/container_tests/bin/healthcheck_tests/efa_checker_single_node.sh
  test/dlc_tests/container_tests/bin/healthcheck_tests/efa_checker_test.sh
  test/dlc_tests/container_tests/bin/healthcheck_tests/nccl_test.sh
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ec2/test_efa.py
  test/dlc_tests/sanity/test_health_check.py
  test/dlc_tests/sanity/test_remote_function_compatibility.py
Labels: build, test, pytorch, ec2, sanity, Size:S, sagemaker_tests

#3356 Release PT 2.0 CU121 images
  release_images_training.yml
Labels: Size:S

#3355 [PyTorch][Test] PT 2.0.1 Cu118 testing fast follow
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ec2/test_efa.py
  test/test_utils/ec2.py
Labels: test, ec2, Size:XS, Size:S

#3358 [Pytorch][Test] PT2.0.1 Cu118 Training tests fast follow continued
  test/dlc_tests/ec2/test_efa.py
  test/test_utils/ec2.py
Labels: test, ec2, Size:XS

#3362 [Pytorch][Release] PT2.0.1 Cu11.8 GPU SM Training release
  release_images_training.yml
Labels: Size:XS

#3360 [BUILD][PYTORCH][NEURON][NEURONX] Add Pytorch Neuron(x) 2.14.1 images
  pytorch/inference/buildspec-1-13-neuron.yml
  pytorch/inference/buildspec-1-13-neuronx.yml
  pytorch/inference/buildspec-neuron.yml
  pytorch/inference/buildspec-neuronx.yml
  pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuron
  pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuron.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx
  pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx.os_scan_allowlist.json
  pytorch/training/buildspec-1-13-neuronx.yml
  pytorch/training/buildspec-neuronx.yml
  pytorch/training/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx
  pytorch/training/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx.os_scan_allowlist.json
Labels: build, pytorch, Size:S

#3363 [BUILD][PYTORCH][NEURON][INFERENCE] Add numpy to explicit install for PT Neuron 2.14.1 inference image
  pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuron
Labels: build, pytorch, Size:XS

#3366 Add Tensorflow Neuron 2.14.1 inference images to release
  release_images_inference.yml
Labels: Size:S

#3367 release TGI v1.1.0
  release_images_inference.yml
Labels: Size:XS

#3368 Add PT Neuron(x) 2.14.1 to release_images
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S
