Repository aws/deep-learning-containers, pull requests merged in 2023-05, with the labels that each got.

#2946 pin invoke version
  src/requirements.txt
  test/requirements.txt
  test/sagemaker_tests/autogluon/inference/requirements.txt
  test/sagemaker_tests/autogluon/training/requirements.txt
  test/sagemaker_tests/huggingface/inference/requirements.txt
  test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
  test/sagemaker_tests/huggingface_tensorflow/training/requirements.txt
  test/sagemaker_tests/mxnet/inference/requirements.txt
  test/sagemaker_tests/mxnet/training/requirements.txt
  test/sagemaker_tests/pytorch/inference/requirements.txt
  test/sagemaker_tests/pytorch/training/requirements.txt
  test/sagemaker_tests/tensorflow/inference/requirements.txt
  test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt
  test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt
Labels: src, test, Size:S, sagemaker_tests

#2953 Add NeuronX TF 2.10.1 release with SDK 2.9.0
  release_images_inference.yml
Labels: Size:XS

#2954 Release only TF 2.10.1 NeuronX with Neuron SDK 2.9.0
  release_images_inference.yml
Labels: Size:S

#2959 Add DJL FasterTransformer release definitions
  release_images_inference.yml
Labels: Size:S

#2908 Expand scope for Codeowners
  .github/CODEOWNERS
Labels: Size:XS

#2960 Add DJL cpu full release definitions
  release_images_inference.yml
Labels: Size:XS

#2782 [huggingface_pytorch_neuronx] Training - update for Transformers to 4.28.1
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/training/buildspec-neuronx.yml
  huggingface/pytorch/training/docker/1.13/py3/sdk2.9.1/Dockerfile.neuronx
  huggingface/pytorch/training/docker/1.13/py3/sdk2.9.1/Dockerfile.neuronx.os_scan_allowlist.json
  huggingface/pytorch/training/docker/build_artifacts/changehostname.c
  huggingface/pytorch/training/docker/build_artifacts/start_with_right_hostname.sh
  src/utils.py
  test/dlc_tests/sanity/test_ecr_scan.py
  test/sagemaker_tests/huggingface_pytorch/training/conftest.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_neuronx.py
Labels: src, build, test, huggingface, sanity, Size:S, sagemaker_tests

#2956 [NEURON][PT][TF][BUILD] Add NeuronX SDK 2.10.0 inference images (TF and PT)
  pytorch/inference/buildspec-1-13-neuronx.yml
  pytorch/inference/buildspec-neuronx.yml
  pytorch/inference/docker/1.13/py3/sdk2.10.0/Dockerfile.neuronx
  pytorch/inference/docker/1.13/py3/sdk2.10.0/Dockerfile.neuronx.os_scan_allowlist.json
  tensorflow/inference/buildspec-2-10-neuronx.yml
  tensorflow/inference/buildspec-neuronx.yml
  tensorflow/inference/docker/2.10/py3/sdk2.10.0/Dockerfile.neuronx
  tensorflow/inference/docker/2.10/py3/sdk2.10.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/test_utils/__init__.py
Labels: build, pytorch, tensorflow, Size:S

#2962 [LMI DLC] add container image update
  available_images.md
Labels: Size:S

#2964 Release HF Training trn1 PT Neuronx images
  release_images_training.yml
Labels: Size:XS

#2963 [NEURON][TF][PT] Add NeuronX SDK 2.10.0 inference images to release
  release_images_inference.yml
Labels: Size:S

#2965 [MISC] Change wording for Neuron supported instance type column
  available_images.md
Labels: Size:S

#2967 Add NeuronX SDK 2.10.0 inference releases to available_images.md
  available_images.md
Labels: Size:XS

#2899 Fix PT2.0 defects: Apex torch._six, training toolkit
  pytorch/training/docker/2.0/py3/Dockerfile.cpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/training/docker/2.0/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  pytorch/training/docker/build_artifacts/mnist.py
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchNccl
  test/requirements.txt
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py
  test/sagemaker_tests/pytorch/training/resources/mnist/mnist.py
  test/sagemaker_tests/pytorch/training/resources/mnist/pytorchddp_throughput_mnist.py
  test/sagemaker_tests/pytorch/training/resources/mnist/smdataparallel_mnist.py
  test/sagemaker_tests/pytorch/training/resources/mnist/smmodelparallel_pt_mnist.py
Labels: build, test, pytorch, ecs, ec2, sanity, Size:XS, Size:S, sagemaker_tests

#2958 [NEURONX][PT][TRAINING][BUILD] Add NeuronX PT training for SDK 2.10.0
  data/ignore_ids_safety_scan.json
  pytorch/training/buildspec-1-13-neuronx.yml
  pytorch/training/buildspec-neuronx.yml
  pytorch/training/docker/1.13/py3/sdk2.10.0/Dockerfile.neuronx
  pytorch/training/docker/1.13/py3/sdk2.10.0/Dockerfile.neuronx.os_scan_allowlist.json
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_neuron.py
  test/test_utils/__init__.py
Labels: build, test, pytorch, Size:S, sagemaker_tests

#2932 [huggingface_pytorch_neuronx] Inference - update for Transformers to 4.28.1
  huggingface/pytorch/inference/buildspec-neuronx.yml
  huggingface/pytorch/inference/docker/1.13/py3/sdk2.9.1/Dockerfile.neuronx
  huggingface/pytorch/inference/docker/1.13/py3/sdk2.9.1/Dockerfile.neuronx.os_scan_allowlist.json
  src/constants.py
  test/sagemaker_tests/huggingface/inference/conftest.py
  test/sagemaker_tests/huggingface/inference/integration/__init__.py
  test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_neuronx_hosting.py
  test/sagemaker_tests/huggingface/inference/resources/code/neuronx_inference.py
  test/sagemaker_tests/huggingface/inference/resources/tiny-distilbert-sst-2/pt_neuronx_model.tar.gz
  test/test_utils/__init__.py
Labels: src, build, test, huggingface, sanity, Size:S, sagemaker_tests

#2974 [NEURONX][PT][TRAINING] Add PT NeuronX training container for SDK 2.10.0 to release_images_tr…
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S

#2976 Release Huggingface Pytorch Neuronx Inference (trn1/inf2) images
  release_images_inference.yml
Labels: Size:XS

#2966 Add HF PT Training Neuronx images to available_images.yml
  available_images.md
Labels: Size:XS

#2977 Add latest PT NeuronX Training image to available_images.md
  available_images.md
  release_images_training.yml
Labels: Size:XS

#2961 fix smart retry
  test/test_utils/__init__.py
  test/test_utils/pytest_cache.py
  test/testrunner.py
Labels: Size:S

#2979 [test] Fix SM Local test parametrization
  test/sagemaker_tests/huggingface_tensorflow/training/integration/conftest.py
  test/sagemaker_tests/pytorch/training/conftest.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py
Labels: test, Size:S, sagemaker_tests

#2973 Fix DDP issues in DLC ec2 performance test
  test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_synthetic
  test/test_utils/ec2.py
Labels: build, pytorch, Size:XS, Size:S

#2980 PyTorch(Studio) - Add ipykernel to dockerfiles
  pytorch/training/docker/2.0/py3/Dockerfile.cpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, pytorch, Size:XS

#2987 Add HF Inference NeuronX containers to available images
  available_images.md
Labels: Size:XS

#2975 [pytorch][build][test]Remove nvgpu package from PT 1.12.1 inference image
  pytorch/inference/docker/1.12/py3/Dockerfile.cpu
  pytorch/inference/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.gpu
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.gpu
  src/image.py
  test/test_utils/__init__.py
Labels: src, build, pytorch, Size:S

#2990 Release pytorch 1.12.1 inference images
  release_images_inference.yml
Labels: Size:S

#2991 [pytorch][release] Patch Release PT 2.0 x86 and graviton
  release_images_inference.yml
Labels: Size:S

#2994 [pytorch][release] patch release PT2.0 graviton
  release_images_inference.yml
Labels: Size:XS

#2992 [PyTorch][Training] Re-Release PT2.0 Training SM
  release_images_training.yml
Labels: Size:XS, Size:S

#2995 [Test][Tensorflow] Add Skips for non g3.8 instances TensorRt
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
Labels: build, test, tensorflow, ec2, Size:XS, Size:S

#2996 [PyTorch][Training] Pin SM Test for PT training
  test/sagemaker_tests/pytorch/training/requirements.txt
Labels: test, Size:XS, sagemaker_tests

#2998 [Test] Add TensorRT build model logic
  test/dlc_tests/container_tests/bin/tensorflow_serving/example/built_models/tftrt_saved_model/assets/trt-serialized-engine.TRTEngineOp_000_000
  test/dlc_tests/container_tests/bin/tensorflow_serving/example/built_models/tftrt_saved_model/fingerprint.pb
  test/dlc_tests/container_tests/bin/tensorflow_serving/example/built_models/tftrt_saved_model/saved_model.pb
  test/dlc_tests/container_tests/bin/tensorflow_serving/example/built_models/tftrt_saved_model/variables/variables.data-00000-of-00001
  test/dlc_tests/container_tests/bin/tensorflow_serving/example/built_models/tftrt_saved_model/variables/variables.index
  test/dlc_tests/container_tests/bin/tensorflow_serving/example/create_tensorrt_model.py
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
Labels: build, test, tensorflow, ec2, Size:S

#2999 Tensorflow ec2 image release
  release_images_inference.yml
Labels: Size:XS

#3001 [PT][NEURON][RELEASE] Add Neuron PT inference image for SDK 2.10.0 to release
  release_images_inference.yml
Labels: Size:XS

#2997 [BUILD][TF][NEURON][INFERENCE] Add Tensorflow 2.10.1 for Neuron SDK 2.10.0
  tensorflow/inference/buildspec-2-10-neuron.yml
  tensorflow/inference/buildspec-neuron.yml
  tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.10.0/Dockerfile.neuron
  tensorflow/inference/docker/2.10/py3/sdk2.10.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/build_artifacts/sagemaker_neuron/multi_model_utils.py
  tensorflow/inference/docker/build_artifacts/sagemaker_neuron/nginx.conf.template
  tensorflow/inference/docker/build_artifacts/sagemaker_neuron/python_service.py
  tensorflow/inference/docker/build_artifacts/sagemaker_neuron/serve.py
  tensorflow/inference/docker/build_artifacts/sagemaker_neuron/tensorflowServing.js
  tensorflow/inference/docker/build_artifacts/sagemaker_neuron/tfs_utils.py
  test/test_utils/__init__.py
Labels: build, tensorflow, Size:S

#3000 Add TF Inference 2.12.1 images to available images
  available_images.md
Labels: Size:XS

#3003 [TF][NEURON][RELEASE] Add Neuron TF2.10.1 inference image for SDK2.10.0
  release_images_inference.yml
Labels: Size:XS

#3005 [PT][NEURON][INFERENCE][DOC] Add Pytorch 1.13.1 Neuron SDK 2.10.0 image to available_images.md
  available_images.md
  release_images_inference.yml
Labels: Size:XS

#3006 [TF][NEURON][INFERENCE][DOC] Add Tensorflow 2.10.1 Neuron SDK 2.10.0 image to available_images.md
  available_images.md
  release_images_inference.yml
Labels: Size:XS

#3007 Add DJL 0.22.1 Neuron SDK 2.10.0 release definitions
  release_images_inference.yml
Labels: Size:XS

#3002 [Build][Test] Tensorflow 2.12 Sagemaker
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/test_tfs.py
Labels: build, test, tensorflow, ec2, Size:S, sagemaker_tests

#3004 [tensorflow][graviton][patch] Update Graviton TFS 2.12 with performance patch
  tensorflow/inference/docker/2.12/py3/Dockerfile.graviton.cpu
Labels: build, test, tensorflow, benchmark, Size:XS

#3009 TF 2.12.1 Sagemaker Release
  release_images_inference.yml
Labels: Size:XS

#3010 [Test][Tensorflow] Pin SM version for SM tests
  test/sagemaker_tests/tensorflow/inference/requirements.txt
Labels: test, Size:XS, sagemaker_tests

#3012 [tensorflow][graviton] Add TFS 2.12.1 graviton to available images.
  available_images.md
  release_images_inference.yml
Labels: Size:S

#3013 Update TF2.12 SM images in available images
  available_images.md
Labels: Size:XS

#3014 [HuggingFace] Update Transformers version to 4.28.1 for PyTorch 1.13 Training and Inference DLCs
  huggingface/pytorch/inference/buildspec.yml
  huggingface/pytorch/training/buildspec-1-13.yml
Labels: build, huggingface, Size:XS

#3030 [pytorch] update TorchServe to 0.8.0 and disable nvgpu metrics on SM gpu
  pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  pytorch/inference/docker/2.0/py3/Dockerfile.graviton.cpu
  pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, pytorch, Size:XS

#3031 [release] Add HF Training PT 2.0 transformers 4.28.1 to release images
  release_images_training.yml
Labels: Size:XS

#3033 [pytorch][release] Patch release PT 2.0 with TS 0.8.0
  release_images_inference.yml
Labels: Size:S

#3035 Release HF PT 2.0 inference images
  release_images_inference.yml
Labels: Size:XS

#3036 Update SM tests for HF to support py310
  test/sagemaker_tests/huggingface/inference/conftest.py
Labels: test, Size:XS, sagemaker_tests

#3008 update the neuron description
  available_images.md
Labels: Size:XS

#3038 [HuggingFace] Update available images PT2.0 Training + Inference
  available_images.md
Labels: Size:XS, Size:S

#3028 [BUILD][PYTORCH][NEURONX] Add 'import torch_neuronx' to neuronx-entrypoint
  pytorch/inference/docker/1.13/py3/sdk2.10.0/Dockerfile.neuronx
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_neuron_hosting.py
  test/test_utils/__init__.py
  test/test_utils/sagemaker.py
Labels: build, test, pytorch, Size:S, sagemaker_tests

#3044 Release HF TGI containers
  release_images_inference.yml
Labels: Size:S

#3045 Add NeuronX Pytorch inference image update to release_images_inference
  release_images_inference.yml
Labels: Size:XS

#3050 Add Huggingface TGI 0.6.0 to available images
  available_images.md
Labels: Size:XS
