Repository aws/deep-learning-containers, pull requests merged in 2023-02, with the labels that each got.

#2669 fix sanity for pt1.11 trcomp
  huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#2672 [MxNet][Inference] Release MxNet 1.9 innference images
  release_images_inference.yml
Labels: Size:S

#2673 [MxNet] [Inference] Fix indentation issues in release_images_inference.yml
  release_images_inference.yml
Labels: Size:S

#2681 chore: add trcomp release config
  release_images_training.yml
Labels: Size:XS

#2682 [Graviton][Pytorch] Update AllowList for Image Patching
  pytorch/inference/docker/1.12/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json
Labels: build, pytorch, Size:S

#2685 [graviton][tensorflow] update ecr allow list for patching
  tensorflow/inference/docker/2.9/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.9/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json
Labels: build, tensorflow, Size:S

#2625 [pt][tf][eia][build]Patch PT 1.5.1 and TF 2.3 eia images
  pytorch/inference/docker/1.5.1/py38/Dockerfile.eia
  pytorch/inference/docker/1.5.1/py38/Dockerfile.eia.os_scan_allowlist.json
  tensorflow/inference/docker/2.3.0/py37/Dockerfile.eia
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist.py
Labels: build, test, pytorch, tensorflow, Size:XS, Size:S, sagemaker_tests

#2695 [EIA] patch release
  release_images_inference.yml
Labels: Size:XS

#2690 doc: update trcomp latest
  available_images.md
Labels: Size:XS

#2657 [pytorch] Enable overwritable TS parameter
  pytorch/inference/docker/build_artifacts/config.properties
Labels: build, pytorch, Size:XS

#2698 [release] Configure release for AG 0.6.2 Training DLCs
  release_images_training.yml
Labels: Size:XS

#2688 [PyTorch][trcomp] update trcomp PT1.13 DLC to add race condition fix feature
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.trcomp.gpu
Labels: build, pytorch, Size:XS

#2701 [autogluon][doc] AutoGluon 0.6.2 available images update
  available_images.md
Labels: Size:XS

#2696 PT-1.13 CVE patching
  pytorch/training/buildspec.yml
  pytorch/training/docker/1.13/py3/Dockerfile.cpu
  pytorch/training/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdataDev
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
Labels: build, test, pytorch, ec2, Size:S

#2705 update release image for PyTorch 1.13.1
  .release_images_template.yml
  release_images_training.yml
Labels: Size:S

#2706 [graviton][pytorch] pin up cryptography
  pytorch/inference/docker/1.12/py3/Dockerfile.graviton.cpu
Labels: build, pytorch, Size:XS, Size:S

#2708 [TensorFlow][Training] TF2.10.1 Release
  release_images_training.yml
Labels: Size:S

#2683 PT-1.11 CVE patching
  pytorch/training/docker/1.11/py3/Dockerfile.cpu
  pytorch/training/docker/1.11/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.11/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.11/py3/cu113/Dockerfile.gpu
  pytorch/training/docker/1.11/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.11/py3/cu115/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.11/py3/cu115/Dockerfile.gpu
  pytorch/training/docker/1.11/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_dgl.py
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#2700 [pytorch]Patch PyTorch 1.12.1
  pytorch/inference/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
Labels: build, pytorch, Size:XS, Size:S

#2699 [tensorflow]Patch Tensorflow 2.11
  tensorflow/inference/docker/2.11/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.11/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, tensorflow, Size:XS, Size:S

#2662 PT-1.12 CVE patching
  pytorch/training/docker/1.11/py3/Dockerfile.cpu
  pytorch/training/docker/1.11/py3/cu113/Dockerfile.gpu
  pytorch/training/docker/1.11/py3/cu115/Dockerfile.gpu
  pytorch/training/docker/1.12/py3/Dockerfile.cpu
  pytorch/training/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.gpu
  pytorch/training/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/1.12/py3/cu116/Dockerfile.gpu
  pytorch/training/docker/1.12/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/Dockerfile.cpu
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
Labels: build, pytorch, Size:XS, Size:S

#2694 fixing issue with TF-graviton benchmark
  test/dlc_tests/benchmark/ec2/tensorflow/inference/test_performance_tensorflow_inference.py
  test/dlc_tests/container_tests/bin/benchmark/tf1_serving_perf.py
  test/dlc_tests/container_tests/bin/benchmark/tf2_serving_perf.py
Labels: src, test, benchmark, Size:XS, Size:S

#2712 [graviton][release] re-release PT 1.12.1 Graviton
  release_images_inference.yml
Labels: Size:S

#2711 [pytorch]Run tests to check for new CVEs in PyTorch inference images
  pytorch/inference/docker/1.12/py3/Dockerfile.cpu
  pytorch/inference/docker/1.12/py3/cu113/Dockerfile.gpu
  pytorch/inference/docker/1.12/py3/cu116/Dockerfile.gpu
Labels: build, pytorch, Size:XS

#2715 Add schema definitions to release PT 1.12 and TF 2.11 images
  release_images_inference.yml
Labels: Size:S

#2714 release pt1.11/1.12/1.13 training images
  release_images_training.yml
Labels: Size:S

#2718 release HF PT1.13
  release_images_training.yml
Labels: Size:S

#2707 [pytorch] Patch 1.13 and fix torchdata test
  pytorch/inference/docker/1.13/py3/Dockerfile.cpu
  pytorch/inference/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
  pytorch/inference/docker/1.13/py3/cu117/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdataDev
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
Labels: build, test, pytorch, ec2, Size:S

#2723 update available images with HF PT1.13
  available_images.md
Labels: Size:XS

#2724 [pytorch][release] patch release PT 1.13.1
  release_images_inference.yml
Labels: Size:S

#2725 Trcomp 1.11 CVE
  huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu
  huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#2721 Trcomp PT-1.13 CVE patching
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.sagemaker.trcomp.gpu.os_scan_allowlist.json
Labels: build, pytorch, Size:XS, Size:S

#2726 [graviton][release] TF 2.9.1 Graviton patch release
  release_images_inference.yml
Labels: Size:S

#2729 Release Trcomps
  .release_images_template.yml
  release_images_training.yml
Labels: Size:S

#2656 Pytorch revamp
  pytorch/training/buildspec.yml
  pytorch/training/docker/1.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  pytorch/training/docker/1.13/py3/cu113/Dockerfile.sagemaker.lite.gpu
  pytorch/training/docker/1.13/py3/cu116/Dockerfile.sagemaker.full.gpu
  pytorch/training/docker/1.13/py3/cu116/Dockerfile.sagemaker.lite.gpu
  pytorch/training/docker/1.13_revamp/py3/Dockerfile.cpu
  pytorch/training/docker/1.13_revamp/py3/cu117/Dockerfile.gpu
  test/dlc_tests/container_tests/bin/dgl_tests/parse_dgl_results.py
  test/dlc_tests/container_tests/bin/dgl_tests/testDGLHelper
  test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
Labels: build, test, pytorch, ec2, Size:S, sagemaker_tests

#2733 Release DJL 0.21.0 images
  release_images_inference.yml
Labels: Size:S

#2731 fix: hf-trcomp-pt-1.11. CVE patching
  huggingface/pytorch/training/buildspec-trcomp.yml
  huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu
Labels: build, huggingface, Size:XS, Size:S

#2736 Patch MX 1.9 inference images
  mxnet/inference/docker/1.9/py3/Dockerfile.cpu
  mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu
Labels: build, mxnet, Size:XS

#2734 Add new region to list of DLC available regions
  available_images.md
Labels: Size:XS

#2735 Update available images with DJL 0.21.0 release
  available_images.md
Labels: Size:XS

#2739 Release MX 1.9 images
  release_images_inference.yml
Labels: Size:S
