Repository aws/deep-learning-containers, pull requests merged in 2023-08, with the labels that each got.

#3216 [eks] eks-patching
  eks_infrastructure/build_param.json
Labels: Size:XS

#3199 [PyTorch] [SM, EC2] Upgrade torchserve version from 0.8.0 to 0.8.1
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  pytorch/inference/docker/2.0/py3/Dockerfile.graviton.cpu
  pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#3212 [huggingface][tensorflow][inference] patch update for HF TFS 2.11
  huggingface/tensorflow/inference/docker/2.11/py3/Dockerfile.cpu
  huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu
  huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:XS, Size:S

#3220 update eks cluster name
  eks_infrastructure/build_param.json
Labels: Size:XS

#3222 [release] patch release HF TFS 2.11 and TFS 2.13 EC2 release
  release_images_inference.yml
Labels: Size:S

#3223 [djl-serving] Release DJL 0.23.0 DeepSpeed 0.9.5 patch
  release_images_inference.yml
Labels: Size:XS

#3225 [release][tensorflow][inference] Release Attempt Two
  release_images_inference.yml
Labels: Size:XS

#3219 [PyTorch] [SM, EC2] Pin mkl version in x86 inference Dockerfiles
  pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, pytorch, Size:XS

#3226 [djl-serving] Release patch for TNX DLC 0.23.0 DJL
  release_images_inference.yml
Labels: Size:XS

#3228 [post release][tensorflow][inference] Update Available images
  available_images.md
Labels: Size:XS

#3204 [tensorflow][training] TF 2.13 SM Currency
  tensorflow/training/buildspec.yml
  tensorflow/training/docker/2.13/py3/Dockerfile.cpu
  tensorflow/training/docker/2.13/py3/cu118/Dockerfile.gpu
  test/dlc_tests/benchmark/ec2/tensorflow/training/test_performance_tensorflow_training.py
  test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_performance_tensorflow_sm_training.py
  test/dlc_tests/ec2/test_smdebug.py
  test/dlc_tests/sanity/test_pre_release.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/local/test_horovod.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smdataparallel.py
Labels: build, test, tensorflow, ec2, benchmark, sanity, Size:S, sagemaker_tests

#3229 [PyTorch] [SM, EC2] Add release image definitions for PT 2.0.1 inference torchserve upgrade
  release_images_inference.yml
Labels: Size:S

#3230 [hf-tgi] Release TGI 0.9.3
  release_images_inference.yml
Labels: Size:XS

#3195 [stabilityai_pytorch][inference] Stability AI Inference DLC
  src/image_builder.py
  stabilityai/pytorch/inference/buildspec.yml
  stabilityai/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
  stabilityai/pytorch/inference/docker/build_artifacts/torchserve-stabilityai-entrypoint.py
  test/dlc_tests/container_tests/bin/security_checks.py
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
  test/dlc_tests/sanity/test_boottime_container_security.py
  test/dlc_tests/sanity/test_pre_release.py
  test/sagemaker_tests/pytorch/inference/integration/__init__.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_stabilityai.py
  test/sagemaker_tests/pytorch/inference/resources/stabilityai/sdxl-v1/model_gpu/.gitignore
  test/sagemaker_tests/pytorch/inference/resources/stabilityai/sdxl-v1/model_gpu/README.md
  test/sagemaker_tests/pytorch/inference/resources/stabilityai/sdxl-v1/model_gpu/code/sdxl_inference.py
  test/testrunner.py
Labels: src, test, ec2, sanity, Size:S, sagemaker_tests

#3221 [Tensorflow] Modify tensorflowServing.js to replace responseBody, requestBody with responseText, requestText respectively
  tensorflow/inference/docker/build_artifacts/sagemaker/tensorflowServing.js
  tensorflow/inference/docker/build_artifacts/sagemaker_neuron/tensorflowServing.js
Labels: build, tensorflow, Size:S

#3231 [djl-serving] Update available images for TNX 0.23.0 and TGI 0.9.3
  available_images.md
Labels: Size:S

#3232 [tensorflow][training] disable SM dataparallel tests for TF 2.13 and above
  test/dlc_tests/release_candidate_integration/test_sm_profiler.py
  test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smdataparallel.py
Labels: test, Size:XS, Size:S, sagemaker_tests

#3233 [tensorflow][inference][sagemaker] TFS 2.13 SM currency
  tensorflow/inference/buildspec.yml
  tensorflow/inference/docker/2.13/py3/Dockerfile.cpu
  tensorflow/inference/docker/2.13/py3/cu118/Dockerfile.gpu
Labels: build, tensorflow, Size:S

#3237 [djl-serving] Patch djl-cpu-full 0.23.0
  release_images_inference.yml
Labels: Size:XS

#3238 [tensorflow][post-release] Update Available images for TF 2.13 SM Training
  available_images.md
Labels: Size:XS

#3234 Skip sagemaker profiler test due to deprecation
  test/dlc_tests/release_candidate_integration/test_sm_profiler.py
Labels: Size:XS

#3247 [djl-serving] CVE patch DJL-FT 22.1 and 21
  release_images_inference.yml
Labels: Size:S

#3248 [djl-serving] CVE patch DJL-CPU-full 22.1 and 21
  release_images_inference.yml
Labels: Size:XS

#3249 [djl-serving] CVE patch DJL-NueronX 0.22.1
  release_images_inference.yml
Labels: Size:XS

#3250 [djl-serving] CVE patch DJL-DeepSpeed 0.23.0/0.22.1/0.21.0
  release_images_inference.yml
Labels: Size:S

#3227 [PyTorch] Update sagemaker-pytorch-inference to 2.0.16
  pytorch/inference/buildspec-1-13-neuron.yml
  pytorch/inference/buildspec-1-13-neuronx.yml
  pytorch/inference/buildspec-1-13.yml
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/buildspec-neuron.yml
  pytorch/inference/buildspec-neuronx.yml
  pytorch/inference/buildspec.yml
Labels: build, pytorch, Size:XS, Size:S

#3255 Re-release PT 2.0.1 inference images
  release_images_inference.yml
Labels: Size:S

#3261 [tensorflow][inference][graviton] Update available images
  available_images.md
Labels: Size:XS

#3262 Add stabilityai_pytorch release image definition
  .release_templates/stabilityai_release_images.yml
  release_images_inference.yml
Labels: Size:S

#3172 [SM DLC PyTorch] Update PT from 2.0.0 to 2.0.1
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/Dockerfile.cpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVD
  test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVDHelper
  test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVDwithInductor
  test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVDwithInductorHelper
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
Labels: src, build, test, pytorch, ec2, Size:S

#3270 PyTorch 2.0.1 EC2 Fix: Increasing PyTorch Training EC2 DLC image size
  pytorch/training/buildspec.yml
Labels: build, pytorch, Size:XS

#3269 Update available images markdown file with SAI release
  available_images.md
Labels: Size:XS

#3272 [Documentation] | [Triton] | Update Triton documentation with v23.06
  available_images.md
Labels: Size:XS

#3274 Turning off the EC2 image builds for the SM pytorch2.0.1 release
  pytorch/training/buildspec.yml
Labels: build, pytorch, Size:S

#3263 [pytorch][tensorflow] Update packages to fix test errors
  pytorch/training/docker/1.13/py3/Dockerfile.cpu
  pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
  tensorflow/inference/docker/2.12/py3/Dockerfile.cpu
  tensorflow/inference/docker/2.12/py3/cu118/Dockerfile.gpu
  tensorflow/training/docker/2.11/py3/Dockerfile.cpu
  tensorflow/training/docker/2.11/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.gpu
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  tensorflow/training/docker/2.12/py3/Dockerfile.cpu
  tensorflow/training/docker/2.12/py3/cu118/Dockerfile.gpu
  test/dlc_tests/sanity/test_utility_installation.py
Labels: build, test, pytorch, tensorflow, sanity, Size:S

#3279 fix il-central-1 account number
  available_images.md
Labels: Size:XS

#3287 Updating release images file for PyTorch 2.0.1
  release_images_training.yml
Labels: Size:XS, Size:S

#3290 Updating available images for PyTorch SM DLC 2.0.1
  available_images.md
Labels: Size:XS

#3123 [test][ec2] Increase EC2 test parallelism
  dlc_developer_config.toml
  src/config.py
  src/start_testbuilds.py
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/test_utils/__init__.py
  test/test_utils/ec2.py
Labels: src, test, ec2, sanity, Size:XS, Size:S

#3240 [EC2][PyTorch 2.0.1] Add P5 Support
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/2.0/py3/cu121/Dockerfile.gpu
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/efa/testEFA
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchRegressionRevised
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ec2/test_efa.py
  test/dlc_tests/ecs/pytorch/training/test_ecs_pytorch_training.py
  test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
  test/dlc_tests/sanity/test_telemetry.py
  test/test_utils/__init__.py
  test/test_utils/sagemaker.py
Labels: build, test, pytorch, ecs, eks, ec2, sanity, Size:S

#3296 [PT20-training-gpu] [CUDA121] Fix typos
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/test_efa.py
Labels: test, ec2, Size:S
