Repository aws/deep-learning-containers, pull requests merged in 2023-03, with the labels that each got.

#2691 Update PT 1.11 inference DLCs
  pytorch/inference/docker/1.11/py3/Dockerfile.cpu
  pytorch/inference/docker/1.11/py3/cu113/Dockerfile.gpu
  pytorch/inference/docker/1.11/py3/cu115/Dockerfile.gpu
  test/dlc_tests/sanity/test_ecr_scan.py
  test/test_utils/security.py
Labels: build, test, pytorch, sanity, Size:XS, Size:S

#2747 [pt 1.11] Update release_images_inference.yml
  release_images_inference.yml
Labels: Size:S

#2752 Release HF PT 1.13 inference images
  release_images_inference.yml
Labels: Size:S

#2754 Update available images markdown with HF PT 1.13 release
  available_images.md
Labels: Size:XS

#2755 Update EKS cluster
  eks_infrastructure/build_param.json
Labels: Size:XS

#2756 [djlserving] Release fastertransformer container
  release_images_inference.yml
Labels: Size:XS

#2758 Add DJL fastertransformer release to available images
  available_images.md
Labels: Size:XS

#2750 [DJLServing] Release patches for 0.19, 0.20, 0.21
  release_images_inference.yml
Labels: Size:S

#2764 Update available images for DJL cpu full release
  available_images.md
Labels: Size:XS

#2765 Pass TFS parameter for mme use case.
  tensorflow/inference/docker/build_artifacts/sagemaker/python_service.py
  tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
Labels: build, tensorflow, Size:XS, Size:S

#2757 Update kubeflow and kfctl versions
  eks_infrastructure/env_setup.sh
  eks_infrastructure/install_cluster_components.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow_custom_kfctl.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/kfctl_aws.yaml
  test/dlc_tests/eks/eks_manifest_templates/mxnet/training/multi_node_gpu_training.yaml
  test/dlc_tests/eks/eks_manifest_templates/mxnet/training/multi_node_training_horovod_mnist.yaml
  test/dlc_tests/eks/eks_manifest_templates/tensorflow/training/multi_node_gpu_training.yaml
Labels: test, eks, Size:XS, Size:S

#2766 Create new k8s clusters
  eks_infrastructure/build_param.json
  eks_infrastructure/delete_cluster.sh
Labels: Size:XS

#2768 Remove conditional installation of aws-iam-authenticator
  eks_infrastructure/env_setup.sh
Labels: Size:XS

#2769 Fix negation error
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
Labels: test, eks, Size:XS

#2770 create tf mainline eks cluster
  eks_infrastructure/build_param.json
Labels: Size:XS

#2773 [DLC][Inference][FasterTransformer][LMI] update the tracker
  release_images_inference.yml
Labels: Size:XS

#2774 Recreate k8s clusters for DLC frameworks
  eks_infrastructure/build_param.json
  test/test_utils/eks.py
Labels: Size:XS

#2777 [Triton] | [Docs] | Add Triton v23.01 to docs
  available_images.md
Labels: Size:XS

#2778 Release autogluon inference v0.7.0
  release_images_inference.yml
Labels: Size:XS

#2772 Testing dlc containers on EKS clusters
  eks_infrastructure/build_param.json
  eks_infrastructure/create_cluster.sh
  test/test_utils/eks.py
  test/testrunner.py
Labels: test, eks, Size:XS, Size:S

#2779 Updating build param json file
  eks_infrastructure/build_param.json
  eks_infrastructure/build_param.template
Labels: Size:XS

#2780 Add reruns statement to canary tests
  test/testrunner.py
Labels: Size:XS

#2762 [NEURON][PT][BUILD] - Release PT1.13 with neuron SDK 2.8.0
  pytorch/training/buildspec-1-13-neuron.yml
  pytorch/training/buildspec-neuron.yml
  pytorch/training/docker/1.13/py3/sdk2.8.0/Dockerfile.neuron
  pytorch/training/docker/1.13/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  test/test_utils/__init__.py
Labels: build, pytorch, Size:XS, Size:S

#2783 Allowlist modification TF2.11
  tensorflow/training/docker/2.11/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/training/docker/2.11/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
Labels: build, tensorflow, Size:S

#2784 Add PT1.13 training Neuron release
  release_images_training.yml
Labels: Size:XS

#2785 Update Neuron Pytorch training image URL
  available_images.md
Labels: Size:XS

#2786 [test] Retry requirements install on failure
  testspec.yml
Labels: Size:XS

#2787 Release Autogluon0.7 training
  release_images_training.yml
Labels: Size:XS

#2746 Update git-secrets regex for additional coverage
  test/dlc_tests/sanity/quick_checks/test_git_secrets.py
Labels: test, sanity, Size:XS

#2789 [Tensorflow] Release TF2.10.1 Inference DLCs
  release_images_inference.yml
Labels: Size:S

#2791 add graviton support for eks
  eks_infrastructure/build_param.json
Labels: Size:XS

#2790 [Tensorflow] Release TF2.9.3 inference images
  release_images_inference.yml
Labels: Size:S

#2793 Release HF TF 2.11 images
  release_images_inference.yml
Labels: Size:S

#2795 Update available images with HF TF containers
  available_images.md
Labels: Size:XS

#2796 [autogluon][test][sagemaker]Add support for py39 version in tests
  test/sagemaker_tests/autogluon/training/conftest.py
Labels: test, Size:XS, sagemaker_tests

#2797 Re-release HF PT 1.13 images
  release_images_inference.yml
Labels: Size:S

#2767 Remove PT1.11 and TF2.8 sm and ec2 inference images from available_imgs.md
  available_images.md
Labels: Size:XS

#2800 [autogluon][doc] AutoGluon 0.7.0 available images update
  available_images.md
Labels: Size:XS

#2801 Add Neuron TF 115 to release images
  release_images_inference.yml
Labels: Size:XS

#2804 release TF2.12 ec2 DLC
  release_images_training.yml
Labels: Size:S

#2805 update available_images.md with TF2.12 EC2 DLC
  available_images.md
Labels: Size:XS

#2742 [PT 2.0] Training EC2 release
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.0/py3/Dockerfile.cpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  pytorch/training/docker/2.0/py3/example/Dockerfile.gpu
  pytorch/training/docker/2.0/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
  test/dlc_tests/benchmark/ec2/pytorch/training/test_performance_pytorch_training.py
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_inductor
  test/dlc_tests/container_tests/bin/pytorch_tests/0001-test-adapt-BERT_pytorch-training-with-gloo-mpi-backend.patch
  test/dlc_tests/container_tests/bin/pytorch_tests/0001-test-ddp_experiment-DLC-patching.patch
  test/dlc_tests/container_tests/bin/pytorch_tests/evaluateResults
  test/dlc_tests/container_tests/bin/pytorch_tests/installOSSPyTorch
  test/dlc_tests/container_tests/bin/pytorch_tests/setupPyTorchBackendTest
  test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVDwithInductor
  test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVDwithInductorHelper
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchAMPwithInductor
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchGloo
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchGlooMpi
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchMpi
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchNccl
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchwithInductor
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchwithInductorHelper
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/ecs/conftest.py
  test/dlc_tests/ecs/pytorch/training/test_ecs_pytorch_training.py
  test/dlc_tests/sanity/test_pre_release.py
  test/dlc_tests/sanity/test_telemetry.py
Labels: build, test, pytorch, ecs, ec2, benchmark, sanity, Size:S

#2809 [pytorch] Disable PT 2.0 SM in buildspecs
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/buildspec.yml
Labels: build, pytorch, Size:S

#2812 [pytorch][inference] Fix pre release test for inference
  test/dlc_tests/sanity/test_pre_release.py
Labels: test, sanity, Size:XS

#2813 pt2 ec2 sanity fix
  test/dlc_tests/sanity/test_telemetry.py
Labels: test, sanity, Size:XS, Size:S

#2818 temporarily remove fastai from pytorch DLC
  pytorch/training/docker/2.0/py3/Dockerfile.cpu
  pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, pytorch, Size:XS

#2815 [pytorch][x86_64][graviton][ec2] PT 2.0.0 Release
  release_images_inference.yml
Labels: Size:S

#2821 Prevent possible telemetry instance hanging from timing out the sanity tests
  test/dlc_tests/sanity/test_telemetry.py
Labels: test, sanity, Size:XS, Size:S

#2822 [pytorch][graviton][release] complete PT 2.0.0 graviton release
  release_images_inference.yml
Labels: Size:XS

#2823 [pytorch][x86_64][release] Release x86_64 PT2.0.0 inference
  release_images_inference.yml
Labels: Size:XS

#2825 add 2.0 to avail images and fix canary
  available_images.md
  test/test_utils/__init__.py
Labels: Size:XS

#2803 [NEURON][TF][BUILD] - Update TF 2.10 image with latest PIP packages versions
  data/ignore_ids_safety_scan.json
  tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  tensorflow/inference/docker/2.10/py3/sdk2.8.0/Dockerfile.neuron
  tensorflow/inference/docker/2.10/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/test_utils/__init__.py
  test/test_utils/security.py
Labels: build, test, tensorflow, ec2, sanity, Size:XS, Size:S

#2824 Improve ec2 backend tests, add logs for telemetry for PT2.0
  release_images_training.yml
  test/dlc_tests/benchmark/ec2/pytorch/training/test_performance_pytorch_training.py
  test/dlc_tests/container_tests/bin/pytorch_tests/0001-test-adapt-BERT_pytorch-training-with-gloo-mpi-backend.patch
  test/dlc_tests/container_tests/bin/pytorch_tests/setupPyTorchBackendTest
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchGlooMpi
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchNccl
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
  test/dlc_tests/sanity/test_telemetry.py
Labels: test, ec2, benchmark, sanity, Size:S

#2829 fix: docker pull fabric timeout
  test/dlc_tests/sanity/test_telemetry.py
  test/test_utils/ec2.py
Labels: test, ec2, benchmark, sanity, Size:XS, Size:S

#2826 [Tensorflow][Inference][Build][Test] Tensorflow Inference 2.11.1 build and test
  tensorflow/inference/buildspec.yml
  tensorflow/inference/docker/2.11/py3/Dockerfile.cpu
  tensorflow/inference/docker/2.11/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.11/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu
  tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, tensorflow, Size:XS, Size:S

#2834 [Release][Tensorflow][Inference] Release TF Inference 2.11.1 images
  release_images_inference.yml
Labels: Size:S
