Repository aws/deep-learning-containers, pull requests merged in 2024-11, with the labels that each got.

#4401 [PyTorch][Inference][EC2] Upgrade torchserve to 0.12.0 in PT 2.4
  pytorch/inference/buildspec-2-4-ec2.yml
  pytorch/inference/buildspec-graviton-2-4-ec2.yml
  pytorch/inference/docker/2.4/py3/Dockerfile.ec2.cpu.core_packages.json
  pytorch/inference/docker/2.4/py3/Dockerfile.ec2.graviton.cpu.core_packages.json
  pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.core_packages.json
  pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.graviton.gpu.core_packages.json
Labels: build, pytorch, Size:S

#4402 [PyTorch][Inference][SageMaker] Clean up unused function set_disable_token_auth_env()
  test/sagemaker_tests/pytorch/inference/integration/__init__.py
  test/sagemaker_tests/pytorch/inference/integration/local/test_serving.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
Labels: build, test, pytorch, Size:S, sagemaker_tests

#4371 Split sanity test into functionality and security for test time reduction
  dlc_developer_config.toml
  src/config.py
  src/constants.py
  src/prepare_dlc_dev_environment.py
  src/send_test_notification.py
  src/start_testbuilds.py
  src/utils.py
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/test_telemetry.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/dlc_tests/sanity/quick_checks/test_prepare_dev_env.py
  test/dlc_tests/sanity/quick_checks/test_sanity_fixture.py
  test/dlc_tests/sanity/test_anaconda.py
  test/dlc_tests/sanity/test_binary_visibility.py
  test/dlc_tests/sanity/test_boottime_container_security.py
  test/dlc_tests/sanity/test_dlc_labels.py
  test/dlc_tests/sanity/test_ecr_scan.py
  test/dlc_tests/sanity/test_health_check.py
  test/dlc_tests/sanity/test_mxnet_blas_mkl.py
  test/dlc_tests/sanity/test_pre_release.py
  test/dlc_tests/sanity/test_pt_s3.py
  test/dlc_tests/sanity/test_remote_function_compatibility.py
  test/dlc_tests/sanity/test_safety_check.py
  test/dlc_tests/sanity/test_safety_report_file.py
  test/dlc_tests/sanity/test_scan_vulnerability_class_functionality.py
  test/dlc_tests/sanity/test_telemetry.py
  test/dlc_tests/sanity/test_torchvision.py
  test/dlc_tests/sanity/test_utility_installation.py
  test/test_utils/__init__.py
  test/testrunner.py
Labels: src, build, test, pytorch, tensorflow, ec2, sanity, Size:S

#4405 Minor fix on telemetry fixture and update skip logging
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/test_telemetry.py
Labels: test, ec2, Size:XS

#4407 Replace functionality_sanity and security_sanity tests with sanity and security tests
  dlc_developer_config.toml
  src/config.py
  src/constants.py
  src/prepare_dlc_dev_environment.py
  src/start_testbuilds.py
  src/utils.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/dlc_tests/sanity/quick_checks/test_prepare_dev_env.py
  test/dlc_tests/sanity/quick_checks/test_required_fixture.py
  test/dlc_tests/sanity/quick_checks/test_sanity_fixture.py
  test/test_utils/__init__.py
Labels: src, build, test, pytorch, sanity, Size:S

#4406 [PyTorch][Inference][SageMaker]PyTorch 2.5.1 Currency Release
  pytorch/inference/buildspec-2-5-sm.yml
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/2.5/py3/Dockerfile.cpu
  pytorch/inference/docker/2.5/py3/Dockerfile.sagemaker.cpu.py_scan_allowlist.json
  pytorch/inference/docker/2.5/py3/cu124/Dockerfile.gpu
  pytorch/inference/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.py_scan_allowlist.json
Labels: build, pytorch, Size:S

#4409 [PyTorch][Inference][EC2] Re-enable autopatch for PT 2.4 Inference EC2 images
  pytorch/inference/buildspec-2-4-ec2.yml
  pytorch/inference/buildspec-graviton-2-4-ec2.yml
Labels: build, pytorch, Size:XS

#4410 [PyTorch][Inference][EC2]PyTorch 2.5.1 Currency Release
  pytorch/inference/buildspec-2-5-ec2.yml
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/2.5/py3/Dockerfile.cpu
  pytorch/inference/docker/2.5/py3/Dockerfile.ec2.cpu.py_scan_allowlist.json
  pytorch/inference/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.py_scan_allowlist.json
  pytorch/inference/docker/2.5/py3/cu124/Dockerfile.gpu
Labels: build, pytorch, Size:S

#4414 [PyTorch][Inference][EC2][SAGEMAKER] Add images to release images yml
  release_images_patches.yml
Labels: Size:S

#4415 Update SMDDP codeowner team
  .github/CODEOWNERS
Labels: Size:XS

#4412 release: add huggingface training 2.3.0 release config
  release_images_training.yml
Labels: Size:XS

#4418 [PyTorch][Inference][SageMaker][EC2] Add images to available images.
  available_images.md
Labels: Size:XS

#4419 [djl][trtllm] adding lmi-trt inference images for patch/release
  release_images_inference.yml
Labels: Size:S

#4413 [PyTorch][Training][EC2] PyTorch 2.5.1 Currency Release
  pytorch/training/buildspec-2-5-ec2.yml
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.5/py3/Dockerfile.cpu
  pytorch/training/docker/2.5/py3/Dockerfile.ec2.cpu.py_scan_allowlist.json
  pytorch/training/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.py_scan_allowlist.json
  pytorch/training/docker/2.5/py3/cu124/Dockerfile.gpu
  test/dlc_tests/benchmark/ec2/pytorch/training/test_performance_pytorch_training.py
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_imagenet
  test/dlc_tests/container_tests/bin/benchmark/run_pytorch_training_performance_gpu_inductor
  test/dlc_tests/container_tests/bin/efa/testEFA
  test/dlc_tests/container_tests/bin/gluonnlp_tests/testNLP
  test/dlc_tests/container_tests/bin/pytorch_tests/testNVApex
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorch
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchNcclVersion
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchRegression
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchwithInductor
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
  test/dlc_tests/container_tests/bin/testCurand
  test/dlc_tests/container_tests/bin/testMXNet
  test/dlc_tests/container_tests/bin/testOpenCV
  test/dlc_tests/container_tests/bin/testPip3Install
  test/dlc_tests/container_tests/bin/testPipInstall
  test/dlc_tests/container_tests/bin/testSmdebug
  test/dlc_tests/container_tests/bin/testSmprofiler
  test/dlc_tests/container_tests/bin/testTF1HVD
  test/dlc_tests/container_tests/bin/testTF2HVD
  test/dlc_tests/container_tests/bin/testTFAddons
  test/dlc_tests/container_tests/bin/testTFKerasHVDAMP
  test/dlc_tests/container_tests/bin/testTFKerasHVDFP32
  test/dlc_tests/container_tests/bin/testTensorBoard
  test/dlc_tests/container_tests/bin/testTensorFlow
  test/dlc_tests/ec2/pytorch/training/test_pytorch_training_2_5.py
  test/dlc_tests/ec2/test_efa.py
Labels: build, test, pytorch, ec2, benchmark, Size:S

#4422 update license file for PT 2.5
  pytorch/training/docker/2.5/py3/Dockerfile.cpu
  pytorch/training/docker/2.5/py3/cu124/Dockerfile.gpu
Labels: build, pytorch, Size:XS

#4403 [pytorch][sagemaker] Add SMDDP binary for PT 2.4
  pytorch/training/buildspec-2-4-sm.yml
  pytorch/training/docker/2.4/py3/Dockerfile.cpu
  pytorch/training/docker/2.4/py3/Dockerfile.sagemaker.cpu.core_packages.json
  pytorch/training/docker/2.4/py3/cu124/Dockerfile.gpu
  pytorch/training/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json
  test/sagemaker_tests/pytorch/training/conftest.py
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#4424 [PyTorch][TensorFlow][Inference] Add dummy arm64 buildspec files
  pytorch/inference/buildspec-arm64.yml
  tensorflow/inference/buildspec-arm64.yml
Labels: build, pytorch, tensorflow, Size:XS

#4425 Add PT 2.5 Training EC2 to release.yml
  release_images_patches.yml
Labels: Size:S

#4423 [PyTorch][Training][SageMaker] PyTorch 2.5.1 Currency Release
  pytorch/training/buildspec-2-5-sm.yml
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.5/py3/Dockerfile.cpu
  pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.py_scan_allowlist.json
  pytorch/training/docker/2.5/py3/cu124/Dockerfile.gpu
  pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.py_scan_allowlist.json
Labels: build, pytorch, Size:S

#4365 [HuggingFace][Neuronx] Training - Optimum Neuron 0.0.25 - Neuron sdk 2.20.0 - Transformers to 4.43.2
  huggingface/pytorch/training/buildspec-neuronx.yml
  huggingface/pytorch/training/docker/2.1/py3/sdk2.20.0/Dockerfile.neuronx
  huggingface/pytorch/training/docker/2.1/py3/sdk2.20.0/Dockerfile.neuronx.os_scan_allowlist.json
  huggingface/pytorch/training/docker/2.1/py3/sdk2.20.0/Dockerfile.neuronx.py_scan_allowlist.json
Labels: build, huggingface, Size:S

#4426 [lmi] patch release for lmi 0.28.0-0.30.0, release for lmi 0.31.0
  release_images_inference.yml
Labels: Size:S

#4420 Add 'arm64' arch type + PyTorch 2.5.1 Inference ARM64 EC2 and SM Currency
  dlc_developer_config.toml
  pytorch/inference/buildspec-arm64-2-5-ec2.yml
  pytorch/inference/buildspec-arm64-2-5-sm.yml
  pytorch/inference/buildspec-arm64.yml
  pytorch/inference/docker/2.5/py3/Dockerfile.arm64.cpu
  pytorch/inference/docker/2.5/py3/Dockerfile.ec2.arm64.cpu.py_scan_allowlist.json
  pytorch/inference/docker/2.5/py3/Dockerfile.sagemaker.arm64.cpu.py_scan_allowlist.json
  pytorch/inference/docker/2.5/py3/cu124/Dockerfile.arm64.gpu
  pytorch/inference/docker/2.5/py3/cu124/Dockerfile.ec2.arm64.gpu.py_scan_allowlist.json
  release/dlc_release_information.py
  release_buildspec.yml
  src/config.py
  src/main.py
  src/prepare_dlc_dev_environment.py
  src/start_testbuilds.py
  src/utils.py
  test/dlc_tests/benchmark/ec2/tensorflow/inference/test_performance_tensorflow_inference.py
  test/dlc_tests/conftest.py
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
  test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py
  test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
  test/dlc_tests/ec2/test_telemetry.py
  test/dlc_tests/ecs/mxnet/inference/test_ecs_mxnet_inference.py
  test/dlc_tests/ecs/pytorch/inference/test_ecs_pytorch_inference.py
  test/dlc_tests/ecs/tensorflow/inference/test_ecs_tensorflow_inference.py
  test/dlc_tests/eks/pytorch/inference/test_eks_pytorch_inference.py
  test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/dlc_tests/sanity/quick_checks/test_generate_coverage_doc.py
  test/dlc_tests/sanity/quick_checks/test_prepare_dev_env.py
  test/dlc_tests/sanity/test_dlc_labels.py
  test/dlc_tests/sanity/test_pre_release.py
  test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/test_tfs.py
  test/test_utils/__init__.py
  test/test_utils/ec2.py
  test/test_utils/sagemaker.py
  test/test_utils/test_reporting.py
Labels: src, build, test, pytorch, tensorflow, ecs, eks, ec2, benchmark, sanity, Size:S, sagemaker_tests

#4429 [djl-serving] release lmi 0.30.0 neuron dlc
  release_images_inference.yml
Labels: Size:S

#4430 Build PT 2.4 with SMDDP
  pytorch/training/buildspec-2-4-sm.yml
  test/test_utils/sagemaker.py
Labels: build, pytorch, Size:XS, Size:S

#4431 [djl] update available images doc with 0.30.0 images
  available_images.md
Labels: Size:S

#4433 Update available_images.md with PT 2.4 training DLC
  available_images.md
Labels: Size:XS

#4432 Pin numpy<2 for PT 2.4 training SM
  pytorch/training/docker/2.4/py3/Dockerfile.cpu
  pytorch/training/docker/2.4/py3/cu124/Dockerfile.gpu
Labels: build, pytorch, Size:S

#4437 [djl-serving] 0.31.0 lmi image
  release_images_inference.yml
Labels: Size:XS

#4438 [djl-serving] 0.31.0 lmi image release
  release_images_inference.yml
Labels: Size:XS

#4439 [djl-serving] patch neuron 0.30.0 neuron dlc
  release_images_inference.yml
Labels: Size:XS

#4440 [djl-serving] 0.31.0 lmi image patch release
  release_images_inference.yml
Labels: Size:XS

#4441 [PyTorch][Inference] Add PT 2.5 ARM64 to release_images
  release_images_patches.yml
Labels: Size:S

#4442 [lmi] remove force_release tag as patch release has been completed an…
  release_images_inference.yml
Labels: Size:XS

#4443 Update default SM local gpu instance type
  test/test_utils/sagemaker.py
Labels: Size:XS

#4444 chore: update release config for new HF Neuronx images
  release_images_training.yml
Labels: Size:XS

#4434 Add Neuron(X) SDK 2.20.2 images to release_images.md
  available_images.md
Labels: Size:XS

#4436 Onboard PT2.5.1 Training Image to AutoPatch
  pytorch/training/buildspec-2-5-ec2.yml
  pytorch/training/buildspec-2-5-sm.yml
  pytorch/training/docker/2.5/py3/Dockerfile.ec2.cpu.core_packages.json
  pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.core_packages.json
  pytorch/training/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.core_packages.json
  pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json
Labels: build, pytorch, Size:S

#4446 Skip torchdata test for >PT 2.1.1 with cu118
  test/dlc_tests/conftest.py
Labels: Size:XS
