Repository aws/deep-learning-containers, pull requests merged in 2024-04, with the labels that each got.

#3804 Patch huggingface pytorch training 1.13
  huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
Labels: build, huggingface, Size:XS

#3805 Add additional ignores
  huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3801 [doc] Add TF 2.14 Graviton DLCs to available images
  available_images.md
Labels: Size:XS

#3806 [djl-serving] 0.27.0 deepspeed image
  release_images_inference.yml
Labels: Size:XS

#3808 [build] remove hf pt 1.8, 1.9, 1.10 cpu & gpu images
  huggingface/pytorch/inference/docker/1.10/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/1.10/py3/Dockerfile.cpu.os_scan_allowlist.json
  huggingface/pytorch/inference/docker/1.10/py3/cu113/Dockerfile.gpu
  huggingface/pytorch/inference/docker/1.10/py3/cu113/Dockerfile.gpu.os_scan_allowlist.json
  huggingface/pytorch/inference/docker/1.8/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/1.8/py3/cu111/Dockerfile.gpu
  huggingface/pytorch/inference/docker/1.9/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/1.9/py3/cu111/Dockerfile.gpu
Labels: build, huggingface, Size:XS, Size:S

#3810 [PyTorch] Add Neuron(X) SDK 2.18 images to release_images.md
  available_images.md
Labels: Size:S

#3813 Resolve CVE-2023-47248 for huggingface-pytorch-inference-neuronx:1.13.1-transformers4.34.1-neuronx-py310-sdk2.15.0-ubuntu20.04
  huggingface/pytorch/inference/buildspec-4-34-1-neuronx.yml
  huggingface/pytorch/inference/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
Labels: build, huggingface, Size:XS, Size:S

#3819 [PyTorch] Add Neuron(X) SDK 2.18.1 images to release_images.md
  available_images.md
Labels: Size:XS

#3821 Adding data to the allowlist
  data/ignore_ids_safety_scan.json
Labels: Size:XS

#3829 [TensorFlow] Re-Release TF2.14 EC2+SM Training Images
  release_images_training.yml
Labels: Size:XS, Size:S

#3816 [djl-serving] 0.27.0 trtllm dlc release
  release_images_inference.yml
Labels: Size:XS

#3830 [djl-serving] 0.27.0 trtllm dlc force release
  release_images_inference.yml
Labels: Size:XS

#3831 [djl-serving] 0.27.0 deepspeed patch image
  release_images_inference.yml
Labels: Size:XS

#3834 Release PT 2.2.1 graviton images
  release_images_inference.yml
Labels: Size:S

#3835 [djl-serving] 0.27.0 trtllm dlc patch release
  release_images_inference.yml
Labels: Size:XS

#3832 Upgrade EFA to 1.31.0, OFI-NCCL Plugin to 1.9.0, and NCCL to 2.21.5
  pytorch/training/buildspec-2-2-ec2.yml
  pytorch/training/buildspec.yml
  pytorch/training/docker/2.2/py3/Dockerfile.cpu
  pytorch/training/docker/2.2/py3/Dockerfile.ec2.cpu.core_packages.json
  pytorch/training/docker/2.2/py3/Dockerfile.sagemaker.cpu.core_packages.json
  pytorch/training/docker/2.2/py3/cu121/Dockerfile.ec2.gpu.core_packages.json
  pytorch/training/docker/2.2/py3/cu121/Dockerfile.gpu
  pytorch/training/docker/2.2/py3/cu121/Dockerfile.sagemaker.gpu.core_packages.json
  test/dlc_tests/container_tests/bin/gdrcopy/test_gdrcopy.sh
  test/sagemaker_tests/pytorch/training/resources/gdrcopy/test_gdrcopy.sh
Labels: build, test, pytorch, Size:S, sagemaker_tests

#3836 Add PT 2.2.1 Graviton images to available_images.md
  available_images.md
Labels: Size:XS

#3837 [djl-serving] add 0.27.0 neuron 2.18.1 container
  release_images_inference.yml
Labels: Size:XS

#3839 Re-enable Autopatch for PyTorch 2.2 Training EC2
  dlc_developer_config.toml
  pytorch/training/buildspec-2-2-ec2.yml
  pytorch/training/docker/2.2/py3/cu121/Dockerfile.gpu
  src/config.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
Labels: src, build, test, pytorch, sanity, Size:S

#3844 [djl-serving] 0.27.0 cpu dlc release
  release_images_inference.yml
Labels: Size:XS

#3845 [djl-serving] 0.27.0 cpu dlc release update to py38
  release_images_inference.yml
Labels: Size:XS

#3843 [doc][djl-serving] update doc with 0.27.0 release images
  available_images.md
Labels: Size:S

#3842 Re-enable Autopatch for PyTorch 2.2 Training SM
  pytorch/training/buildspec.yml
Labels: build, test, pytorch, Size:XS, Size:S, sagemaker_tests

#3846 Onboard PyTorch 2.2 Graviton Inference images to autopatch
  pytorch/inference/buildspec-graviton.yml
  pytorch/inference/docker/2.2/py3/Dockerfile.ec2.graviton.cpu.core_packages.json
  pytorch/inference/docker/2.2/py3/Dockerfile.ec2.graviton.cpu.py_scan_allowlist.json
  pytorch/inference/docker/2.2/py3/Dockerfile.sagemaker.graviton.cpu.core_packages.json
  pytorch/inference/docker/2.2/py3/Dockerfile.sagemaker.graviton.cpu.py_scan_allowlist.json
Labels: build, pytorch, Size:S

#3851 Release Triton v24.03
  release_images_inference.yml
Labels: Size:XS

#3852 patching hf pt training neuronx for cve
  huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
Labels: build, huggingface, Size:XS

#3856 Release PyTorch 2.1 Inference Autopatch
  release_images_inference.yml
Labels: Size:S

#3854 patching/allowlisting hf pt neuronx training for Pillow, idna, and pi…
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
  huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3857 resolving idna vuln instead of ignoring
  huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
  huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3860 fixing safety scan ignore for neuronx
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
Labels: build, huggingface, Size:XS

#3859 Onboard PyTorch 2.1 Graviton DLC to Autopatch
  pytorch/inference/buildspec-graviton-2-1.yml
  pytorch/inference/docker/2.1/py3/Dockerfile.ec2.graviton.cpu.core_packages.json
  pytorch/inference/docker/2.1/py3/Dockerfile.ec2.graviton.cpu.py_scan_allowlist.json
  pytorch/inference/docker/2.1/py3/Dockerfile.graviton.cpu
  pytorch/inference/docker/2.1/py3/Dockerfile.sagemaker.graviton.cpu.core_packages.json
  pytorch/inference/docker/2.1/py3/Dockerfile.sagemaker.graviton.cpu.py_scan_allowlist.json
Labels: build, pytorch, Size:S

#3861 Release PyTorch 2.1 Graviton Autopatch
  release_images_inference.yml
Labels: Size:S

#3864 [PyTorch] Add Neuron(X) SDK 2.18.2 images to release_images.md
  available_images.md
Labels: Size:XS

#3858 [Doc] Update Triton doc
  available_images.md
Labels: Size:S
