Repository aws/deep-learning-containers, pull requests merged in 2024-01, with the labels that each got.

#3595 Release PT 1.13 training sagemaker
  release_images_training.yml
Labels: Size:XS

#3596 remove gpu from release config
  release_images_training.yml
Labels: Size:XS

#3594 SAI Vulnerability Fixes
  release_images_inference.yml
  stabilityai/pytorch/inference/buildspec.yml
  stabilityai/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.sagemaker.gpu
  test/sagemaker_tests/pytorch/inference/integration/local/test_serving.py
  test/sagemaker_tests/pytorch/inference/requirements.txt
  test/test_utils/__init__.py
Labels: test, Size:XS, Size:S, sagemaker_tests

#3598 Patch huggingface pytorch training 2.0
  release_images_training.yml
Labels: Size:XS

#3601 Update doc for Triton
  available_images.md
Labels: Size:XS

#3605 Release HF PT 2.0 images
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
  release_images_inference.yml
Labels: build, huggingface, Size:S

#3607 Add temp ignore for HF PT inference 2.0
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3608 Add temp ignore for HF PT inference 2.0
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3609 Fix broken inference test
  test/sagemaker_tests/huggingface/inference/integration/local/test_serving.py
  test/sagemaker_tests/huggingface/inference/requirements.txt
Labels: test, Size:XS, sagemaker_tests

#3610 Fix release_images_inference.yml
  release_images_inference.yml
Labels: Size:XS

#3534 [Build] Code refactoring for AutoPatching
  miscellaneous_dockerfiles/Dockerfile.autopatch
  miscellaneous_scripts/derive_history.py
  miscellaneous_scripts/dockerfile_patch_script.sh
  src/constants.py
  src/patch_helper.py
  src/safety_report_generator.py
  src/utils.py
  tensorflow/inference/buildspec-2-12.yml
  test/dlc_tests/sanity/test_ecr_scan.py
  test/dlc_tests/sanity/test_pre_release.py
  test/test_utils/__init__.py
  test/test_utils/security.py
Labels: src, build, test, tensorflow, sanity, Size:S, no-pr-activity

#3540 [Build][Test] Add logic for image shift for AutoPatch Images
  image_transfer_buildspec.yml
  src/image_transfer.py
  test/test_utils/__init__.py
Labels: src, Size:S, no-pr-activity

#3611 Patch CVE-2023-7104
  huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, huggingface, Size:XS

#3612 Release Triton v23.12
  release_images_inference.yml
Labels: Size:XS

#3614 Update Triton v23.12
  available_images.md
Labels: Size:XS

#3615 [djl-serving] patch djl 0.24, 0.25 and release 0.26 TNX containers
  release_images_inference.yml
Labels: Size:S

#3617 Fix release_images ymls
  release_images_training.yml
Labels: Size:XS

#3618 [djl-serving] 0.26.0 deepspeed image
  release_images_inference.yml
Labels: Size:S

#3619 [djl-serving] correct the typo for python
  release_images_inference.yml
Labels: Size:XS

#3620 [djl-serving] 0.26.0 trt llm release
  release_images_inference.yml
Labels: Size:XS

#3621 [djl-serving] 0.26.0 cpu image release
  release_images_inference.yml
Labels: Size:XS

#3622 [doc][djl-serving] update doc with 0.26.0 release images
  available_images.md
Labels: Size:XS

#3623 Add temp ignore for HF PT training 2.0
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3625 [djl-serving] patch 0.24 fastertransformer containers
  release_images_inference.yml
Labels: Size:S

#3624 [djl-serving] patch 0.24, 0.25, 0.26 deepspeed dlc images
  release_images_inference.yml
Labels: Size:S

#3629 TGI NeuronX Available Image
  available_images.md
Labels: Size:XS

#3628 [Build] Pin safety version
  src/utils.py
Labels: src, Size:XS

#3613 [PyTorch] [Training] [2.1] [SageMaker] Enabling PyTorch Verbose Logging for advanced modules
  pytorch/training/docker/2.1/py3/Dockerfile.cpu
  pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu
Labels: build, pytorch, Size:XS

#3633 [djl-serving] patch 0.24 and 0.25 cpu images
  release_images_inference.yml
Labels: Size:S

#3626 [djl-serving] patch 0.24 and 0.25 neuronx containers
  release_images_inference.yml
Labels: Size:XS, Size:S

#3640 Release TF 2.12.1 Inference Images
  release_images_inference.yml
Labels: Size:S

#3644 Add G5 filter list for HF inference tests
  test/sagemaker_tests/huggingface/inference/conftest.py
Labels: test, Size:XS, sagemaker_tests

#3641 fix: conditionally skip peft_sft:test_diffusers for hf-pt training co…
  test/sagemaker_tests/huggingface_pytorch/training/conftest.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/__init__.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_peft_sft.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_smdp.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_smmp.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_trcomp.py
Labels: test, Size:S, sagemaker_tests

#3642 Add Exception to Image Transfer and base_repo to PR caller for AutoPatching
  src/autopr_caller.py
  src/image_transfer.py
Labels: src, Size:XS, Size:S

#3646 Temp ignore new vulnerabilities to release HF PT 2.0 images
  .github/CODEOWNERS
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:XS

#3647 Update HF PT training ignore and dockerfile
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3648 Update awscli for HF PT training
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
Labels: build, huggingface, Size:XS

#3650 Change SM tests for PT/TF inference images to run on G5
  .github/workflows/black.yml
  test/sagemaker_tests/pytorch/inference/conftest.py
  test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
Labels: test, Size:XS, Size:S, sagemaker_tests

#3654 Update test instances for HF PT Training
  test/test_utils/sagemaker.py
Labels: Size:XS

#3655 Add temp ignore for HF PT training 2.0
  huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
Labels: build, huggingface, Size:S

#3656 Release PyTorch Images
  release_images_inference.yml
Labels: Size:XS

#3659 Register custom pytest markers to resolve warnings
  test/sagemaker_tests/huggingface_pytorch/training/conftest.py
  test/sagemaker_tests/huggingface_pytorch/training/integration/__init__.py
Labels: test, Size:XS, Size:S, sagemaker_tests

#3383 separate sagemaker jobs
  .github/PULL_REQUEST_TEMPLATE.md
  dlc_developer_config.toml
  src/config.py
  src/constants.py
  src/start_testbuilds.py
  src/utils.py
  test/dlc_tests/conftest.py
  test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
  test/test_utils/__init__.py
  test/testrunner.py
Labels: src, build, test, pytorch, sanity, Size:S, no-pr-activity

#3658 Parallelize venv installation in quick checks
  test/test_utils/test_reporting.py
Labels: Size:S

#3662 [djl-serving] patch 0.26.0 deepspeed dlc
  release_images_inference.yml
Labels: Size:S

#3663 [djl-serving] 0.26 trtllm dlc patch release
  release_images_inference.yml
Labels: Size:XS

#3664 [djl-serving] 0.26.0 tnx dlc patch release
  release_images_inference.yml
Labels: Size:XS

#3665 [djl-serving] 0.26.0 cpu dlc patch release
  release_images_inference.yml
Labels: Size:XS
