Repository aws/deep-learning-containers, pull requests merged in 2025-02, with the labels that each got.

#4530 PT 2.2 end of support
  available_images.md
  release_images_patches.yml
Labels: Size:S

#4534 dummy commit
  release_images_patches.yml
Labels: Size:XS

#4536 Uncomment PT 2.3 graviton release
  release_images_patches.yml
Labels: Size:S

#4545 [lmi] add v14 container for lmi
  release_images_inference.yml
Labels: Size:XS

#4546 [lmi][fix] fix python version for release pipeline
  release_images_inference.yml
Labels: Size:XS

#4541 Patch 2025 02 07
  huggingface/pytorch/training/buildspec.yml
  huggingface/pytorch/training/docker/2.3/py3/cu121/Dockerfile.gpu
  release_images_training.yml
  test/dlc_tests/sanity/test_utility_installation.py
Labels: build, test, huggingface, sanity, Size:S

#4542 Patch 2025 02 07 hf pt training neuronx
  huggingface/pytorch/training/buildspec-neuronx.yml
  huggingface/pytorch/training/docker/2.1/py3/sdk2.20.0/Dockerfile.neuronx
  release_images_training.yml
Labels: build, test, huggingface, sanity, Size:XS, Size:S

#4550 Restore the rest of graviton/arm64 pipelines
  release_images_patches.yml
Labels: Size:S

#4535 [PyTorch][Inference][EC2][SageMaker] Pytorch 2.6.0 Currency Release
  pytorch/inference/buildspec-2-6-ec2.yml
  pytorch/inference/buildspec-2-6-sm.yml
  pytorch/inference/buildspec.yml
  pytorch/inference/docker/2.6/py3/Dockerfile.cpu
  pytorch/inference/docker/2.6/py3/cu124/Dockerfile.gpu
  test/dlc_tests/conftest.py
  test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
Labels: build, test, pytorch, sanity, Size:S

#4557 Add Tensorflow 2.18 Inference arm64 Image to Release
  release_images_patches.yml
Labels: Size:S

#4561 Add arm64 TF2.18 Inf to available images
  available_images.md
Labels: Size:XS

#4563 Patch cuda compat mounting on PT 2.6 Inference SM
  pytorch/inference/buildspec-2-6-sm.yml
  pytorch/inference/docker/2.6/py3/cu124/Dockerfile.gpu
  pytorch/inference/docker/build_artifacts/start_cuda_compat.sh
  pytorch/inference/docker/build_artifacts/torchserve-entrypoint.py
Labels: build, pytorch, Size:S

#4562 Patch cuda compat mounting on TF 2.18 Training SM
  tensorflow/training/buildspec-2-18-sm.yml
  tensorflow/training/docker/2.18/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.gpu
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/training/docker/build_artifacts/dockerd-entrypoint.py
  tensorflow/training/docker/build_artifacts/start_cuda_compat.sh
Labels: build, tensorflow, Size:S

#4564 Onboard TF218 Arm64 to autopatch
  tensorflow/inference/buildspec-arm64-2-18-ec2.yml
  tensorflow/inference/buildspec-arm64-2-18-sm.yml
  tensorflow/inference/docker/2.18/py3/Dockerfile.ec2.arm64.cpu.core_packages.json
  tensorflow/inference/docker/2.18/py3/Dockerfile.sagemaker.arm64.cpu.core_packages.json
Labels: build, tensorflow, Size:S

#4559 Mount cuda-compat by default with new nvidia-container-toolkit for PT SM images
  miscellaneous_dockerfiles/Dockerfile.autopatch
  miscellaneous_scripts/dockerfile_patch_script.sh
  pytorch/training/docker/build_artifacts/start_cuda_compat.sh
  pytorch/training/docker/build_artifacts/start_with_right_hostname.sh
  src/patch_helper.py
Labels: src, build, pytorch, tensorflow, Size:S

#4566 Release PyTorch 2.6 Inf SM DLC
  release_images_patches.yml
Labels: Size:S

#4570 add Python 312 support
  test/sagemaker_tests/pytorch/inference/conftest.py
  test/test_utils/__init__.py
  test/test_utils/sagemaker.py
Labels: test, Size:XS, sagemaker_tests

#4573 delete whitespace
  available_images.md
Labels: Size:XS

#4574 Add PT2.6 x86 Inf EC2 to release
  release_images_patches.yml
Labels: Size:S

#4567 Patch CUDA Compat mounting for TF inference
  tensorflow/inference/buildspec-2-16-sm.yml
  tensorflow/inference/buildspec-2-18-sm.yml
  tensorflow/inference/docker/2.16/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.16/py3/cu122/Dockerfile.gpu
  tensorflow/inference/docker/2.16/py3/cu122/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.18/py3/cu122/Dockerfile.gpu
  tensorflow/inference/docker/2.18/py3/cu122/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/inference/docker/build_artifacts/dockerd_entrypoint.sh
  tensorflow/inference/docker/build_artifacts/start_cuda_compat.sh
Labels: build, test, tensorflow, ec2, Size:S

#4569 [PyTorch][Inference][ARM64] PT 2.6.0 Currency
  pytorch/inference/buildspec-arm64-2-6-ec2.yml
  pytorch/inference/buildspec-arm64-2-6-sm.yml
  pytorch/inference/buildspec-arm64.yml
  pytorch/inference/docker/2.6/py3/Dockerfile.arm64.cpu
  pytorch/inference/docker/2.6/py3/cu124/Dockerfile.arm64.gpu
Labels: build, pytorch, Size:S

#4579 Add PT 2.6 ARM64 Inference to release
  release_images_patches.yml
Labels: Size:S

#4580 Add PYTHON to package manager
  test/test_utils/security.py
Labels: build, pytorch, Size:XS, Size:S

#4582 fix start_host_with_right_name not found
  miscellaneous_dockerfiles/Dockerfile.autopatch
  miscellaneous_scripts/dockerfile_patch_script.sh
Labels: Size:XS

#4583 Onboard TF 2.16/2.18 Infrence SM to autopatch
  tensorflow/inference/buildspec-2-16-sm.yml
  tensorflow/inference/buildspec-2-18-sm.yml
Labels: build, tensorflow, Size:XS

#4584 Add PT 2.6 ARM64 Inference to available_images
  available_images.md
Labels: Size:XS

#4586 Fix canary python version
  test/test_utils/__init__.py
Labels: Size:XS

#4554 Delete EKS Cluster v1.25 and update to v1.32
  eks_infrastructure/build_param.json
  eks_infrastructure/cluster-autoscalar-autodiscover.yaml
  eks_infrastructure/create_cluster.sh
  eks_infrastructure/env_setup.sh
  eks_infrastructure/helper.sh
  eks_infrastructure/new_operation.sh
  eks_infrastructure/upgrade_operation.sh
  test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
  test/test_utils/eks.py
Labels: build, test, pytorch, eks, Size:XS, Size:S

#4588 Add PT2.6 Inf images to available images
  available_images.md
Labels: Size:XS

#4589 Create EKS Cluster v1.32 MAINLINE with gpu nodegroup g5 instance
  eks_infrastructure/build_param.json
Labels: Size:XS

#4590 patch pt2.4
  pytorch/training/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json
  pytorch/training/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, pytorch, Size:S

#4548 Use pipeline execution id instead of source version for initiator tag
  src/image_builder.py
Labels: src, Size:XS

#4597 Add KUL
  available_images.md
Labels: Size:XS

#4596 updating disable_sm_tag for HF pytorch 2.3.0
  release_images_inference.yml
Labels: Size:XS
