Repository aws/deep-learning-containers, pull requests merged in 2025-08, with the labels that each got.

#5093 Tensorflow Inference 2.18 & 2.19 CVE patch
  tensorflow/inference/buildspec-2-18-ec2.yml
  tensorflow/inference/buildspec-2-18-sm.yml
  tensorflow/inference/buildspec-2-19-sm.yml
  tensorflow/inference/docker/2.18/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.18/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.18/py3/cu122/Dockerfile.ec2.gpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.18/py3/cu122/Dockerfile.gpu
  tensorflow/inference/docker/2.18/py3/cu122/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
  tensorflow/inference/docker/2.19/py3/cu122/Dockerfile.gpu
Labels: build, tensorflow, Size:S, authorized

#5121 update vllm to v0.10.0
  release_images_general.yml
  vllm/CHANGELOG.md
  vllm/buildspec.yml
  vllm/x86_64/gpu/Dockerfile
Labels: Size:XS, Size:S, authorized

#5128 AutoGluon 1.4.0 DLC Release
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S, authorized

#5129 disable vllm EKS test on mainline pipeline
  test/testrunner.py
Labels: Size:XS, authorized

#5126 Onboard tensorflow inference 2.18 and 2.19 to autopatch
  tensorflow/inference/buildspec-2-18-ec2.yml
  tensorflow/inference/buildspec-2-18-sm.yml
  tensorflow/inference/buildspec-2-19-sm.yml
Labels: build, tensorflow, Size:XS, authorized

#5136 AutoGluon 1.4.0 DLC Release
  available_images.md
  release_images_inference.yml
  release_images_training.yml
Labels: Size:S, authorized

#5082 Link to HF updated doc
  available_images.md
Labels: Size:S, authorized

#5142 Test pt 26
  test/dlc_tests/container_tests/bin/pytorch_tests/evaluateResults
  test/dlc_tests/container_tests/bin/pytorch_tests/installOSSPyTorch
  test/dlc_tests/container_tests/bin/pytorch_tests/installPyTorchBenchmarkRepository
  test/dlc_tests/container_tests/bin/pytorch_tests/setupPyTorchBackendTest
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchGlooMpi
  test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchNccl
Labels: Size:S, authorized

#5148 adding CVE-2024-48063 for pytorch training neuronx 2.1.2
  huggingface/pytorch/training/docker/2.1/py3/sdk2.20.0/Dockerfile.neuronx.os_scan_allowlist.json
Labels: build, huggingface, Size:S, authorized

#5159 fix package_version_regression for PT27 Sagemaker
  pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
Labels: build, pytorch, Size:XS, authorized

#5157 Upgrade verions
  huggingface/pytorch/training/docker/2.6/py3/cu126/Dockerfile.gpu
Labels: build, huggingface, Size:XS, Size:S, authorized

#5170 Skipping sagemaker gdrcopy and efa tests
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
  test/sagemaker_tests/pytorch/training/integration/sagemaker/test_gdrcopy.py
Labels: test, Size:XS, sagemaker_tests, authorized

#5165 Build cuda129 base
  base/buildspec-cu128-ubuntu24.yml
  base/buildspec-cu129-ubuntu22.yml
  base/buildspec.yml
  base/x86_64/gpu/cu128/ubuntu24.04/Dockerfile
  base/x86_64/gpu/cu129/ubuntu22.04/Dockerfile
  dlc_developer_config.toml
  scripts/install_cuda.sh
Labels: Size:S, authorized

#4986 Adding EC2 tests on vLLM DLC
  test/dlc_tests/container_tests/bin/efa/testEFA
  test/dlc_tests/ec2/test_efa.py
  test/test_utils/ec2.py
  test/testrunner.py
  test/vllm/ec2/infra/setup_ec2.py
  test/vllm/ec2/test_artifacts/test_ec2.py
  test/vllm/ec2/utils/fsx_utils.py
  test/vllm/ec2/utils/head_node_setup.sh
  test/vllm/ec2/utils/run_vllm_benchmark_single_node.sh
  test/vllm/ec2/utils/setup_fsx_vllm.sh
  test/vllm/ec2/utils/worker_node_setup.sh
  test/vllm/trigger_test.py
  vllm/buildspec.yml
Labels: test, ec2, Size:XS, Size:S, authorized

#5185 Add cu128 ul22 base image to release
  release_images_general.yml
Labels: Size:XS, authorized

#5187 enable vLLM EKS EC2 test on pipeline
  test/testrunner.py
  test/vllm/eks/eks_test.py
Labels: Size:XS, authorized

#5176 Fix package dependencies and form data cve
  tensorflow/training/buildspec-2-18-sm.yml
  tensorflow/training/docker/2.18/py3/Dockerfile.cpu
  tensorflow/training/docker/2.18/py3/Dockerfile.sagemaker.cpu.core_packages.json
  tensorflow/training/docker/2.18/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.gpu
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.sagemaker.gpu.core_packages.json
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Labels: build, tensorflow, Size:XS, Size:S, authorized

#5192 update vllm to v0.10.1
  release_images_general.yml
  vllm/CHANGELOG.md
  vllm/buildspec.yml
  vllm/x86_64/gpu/Dockerfile
Labels: Size:S, authorized

#5191 Add condition to check instance type for VLLM EC2
  test/testrunner.py
  test/vllm/trigger_test.py
Labels: Size:XS, authorized

#5184 Disable PT 2.7 Autopatch and Onboard BuildX
  pytorch/training/buildspec-2-7-sm.yml
  pytorch/training/docker/2.7/py3/Dockerfile.cpu
  pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.gpu
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
  src/image.py
Labels: src, build, pytorch, Size:XS, Size:S, authorized

#5196 add pr context and modify condition
  test/vllm/trigger_test.py
Labels: Size:XS, authorized

#5199 update vllm to v0.10.1.1
  release_images_general.yml
  vllm/CHANGELOG.md
  vllm/buildspec.yml
  vllm/x86_64/gpu/Dockerfile
Labels: Size:XS, authorized

#5203 change vllm release version
  release_images_general.yml
  vllm/CHANGELOG.md
  vllm/buildspec.yml
Labels: Size:XS, authorized

#5202 Build Base cu128 with sqlite
  base/x86_64/gpu/cu128/ubuntu22.04/Dockerfile
Labels: Size:XS, authorized

#5193 TF 2.18 Training SM pin nccl to version<13
  .github/PULL_REQUEST_TEMPLATE.md
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.gpu
Labels: src, build, test, tensorflow, ec2, Size:XS, Size:S, authorized

#5171 Build PT27 training with DLC Base
  pytorch/training/buildspec-2-7-ec2.yml
  pytorch/training/buildspec-2-7-sm.yml
  pytorch/training/docker/2.7/py3/Dockerfile.ec2.cpu.core_packages.json
  pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json
  pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.py_scan_allowlist.json
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.ec2.gpu.core_packages.json
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.gpu
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.py_scan_allowlist.json
  scripts/setup_oss_compliance.sh
  test/dlc_tests/ec2/pytorch/training/common_cases.py
Labels: build, test, pytorch, ec2, Size:S, authorized

#5216 Build ec2 with MAX_JOBS=18
  pytorch/training/docker/2.7/py3/Dockerfile.ec2.cpu.core_packages.json
  pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.ec2.gpu.core_packages.json
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.gpu
  pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
Labels: build, pytorch, Size:S, authorized

#5220 Pin boto3 and awscli versions in test
  test/requirements.txt
Labels: Size:XS, authorized

#5224 Pin pytest-rerunfailures versions
  test/requirements.txt
Labels: Size:XS, authorized
