Repository aws/deep-learning-containers, pull requests merged in 2025-09, with the labels that each got.

#5231 add PT 2.8 images to available images
  available_images.md
Labels: Size:XS, authorized

#5233 Build vllm to check CVEs
  src/image.py
Labels: src, Size:XS, authorized

#5154 [VLLM][ARM64] Currency Release
  dlc_developer_config.toml
  scripts/install_efa.sh
  test/dlc_tests/sanity/test_boottime_container_security.py
  test/dlc_tests/sanity/test_dlc_labels.py
  test/dlc_tests/sanity/test_ecr_scan.py
  test/dlc_tests/sanity/test_pre_release.py
  test/vllm/ec2/infra/setup_ec2.py
  test/vllm/ec2/test_artifacts/test_ec2.py
  test/vllm/ec2/utils/run_vllm_on_arm64.sh
  test/vllm/ec2/utils/setup_fsx_vllm.sh
  test/vllm/trigger_test.py
  vllm/arm64/gpu/Dockerfile.arm64
  vllm/buildspec-arm64.yml
Labels: src, test, sanity, Size:S, Size:XL, authorized

#5257 Fix key pair file deletion logic during efa test
  test/dlc_tests/conftest.py
  test/testrunner.py
Labels: Size:XS, Size:S, Size:M, authorized

#5264 change vllm version to v0.10.2
  test/dlc_tests/sanity/test_boottime_container_security.py
  test/dlc_tests/sanity/test_pre_release.py
  test/vllm/ec2/test_artifacts/test_ec2.py
  test/vllm/ec2/utils/setup_fsx_vllm.sh
  vllm/arm64/gpu/Dockerfile.arm64
  vllm/buildspec-arm64.yml
Labels: src, test, sanity, Size:XS, Size:S, Size:M, authorized

#5270 pin prior EKS AMI for vllm eks test
  test/vllm/eks/test_artifacts/large-model-nodegroup.yaml
Labels: Size:XS, authorized

#5256 chore: patch libxml2 cve
  data/ignore_ids_safety_scan.json
  huggingface/pytorch/inference/docker/2.6/py3/Dockerfile.cpu
  huggingface/pytorch/inference/docker/2.6/py3/cu124/Dockerfile.gpu
Labels: build, test, huggingface, Size:S, Size:L, Size:XL, sagemaker_tests, authorized

#5252 add vllm arm64 to release
  release_images_general.yml
Labels: Size:XS, authorized

#5277 update vllm x86 to 0.10.2
  vllm/buildspec.yml
  vllm/x86_64/gpu/Dockerfile
Labels: Size:XS, authorized

#5299 Patch tf2.18 SM image
  tensorflow/training/docker/2.18/py3/Dockerfile.cpu
  tensorflow/training/docker/2.18/py3/Dockerfile.sagemaker.cpu.core_packages.json
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.gpu
  tensorflow/training/docker/2.18/py3/cu125/Dockerfile.sagemaker.gpu.core_packages.json
Labels: build, tensorflow, Size:XS, Size:S, authorized

#5315 [djl-serving] Add 0.34.0 lmi image release
  release_images_inference.yml
Labels: Size:XS, authorized
